import type { AssetClassSlug } from "./investments/asset-class-slugs";
import type { AssetTypeId } from "./investments/asset-types";
import cmaDefaults from "./cma-defaults.generated.json";

export interface SeedAssetClass {
  name: string;
  /** Optional stable slug used to look up engine-referenced classes
   * (e.g. "inflation") without relying on a human-edited name. */
  slug?: AssetClassSlug;
  geometricReturn: number;
  arithmeticMean: number;
  volatility: number;
  pctOrdinaryIncome: number;
  pctLtCapitalGains: number;
  pctQualifiedDividends: number;
  pctTaxExempt: number;
  assetType: AssetTypeId;
}

export interface SeedModelPortfolio {
  name: string;
  description: string;
  allocations: { assetClassName: string; weight: number }[];
}

// Asset-class CMAs (geometric/arithmetic returns + volatility) and the
// correlation matrix (further below) are loaded from cma-defaults.generated.json,
// a committed artifact regenerated by scripts/recompute-cma.ts. Structural fields
// (name/slug/assetType/tax composition) are carried forward unchanged by that
// script; only geometricReturn/arithmeticMean/volatility and the correlations
// change on a recompute. Historically the geometric return + volatility came
// from a standard 14-asset CMA set, with arithmetic mean derived as
// `geometric + σ²/2` (log-normal convergence) — kept as a stored field because
// the engine reads it directly.
export const DEFAULT_ASSET_CLASSES: SeedAssetClass[] =
  cmaDefaults.assetClasses as SeedAssetClass[];

// Fail fast if the generated file drifts from engine expectations.
if (DEFAULT_ASSET_CLASSES.length !== 16) {
  throw new Error(
    `cma-seed: expected 16 asset classes, got ${DEFAULT_ASSET_CLASSES.length}`,
  );
}

export const DEFAULT_MODEL_PORTFOLIOS: SeedModelPortfolio[] = [
  {
    name: "Conservative (30/70)",
    description: "30% equity / 70% fixed income and alternatives",
    allocations: [
      { assetClassName: "US Large Cap", weight: 0.15 },
      { assetClassName: "US Mid Cap", weight: 0.05 },
      { assetClassName: "Global ex-US Stock Market", weight: 0.05 },
      { assetClassName: "REIT", weight: 0.05 },
      { assetClassName: "Short Term Treasury", weight: 0.15 },
      { assetClassName: "10-year Treasury", weight: 0.15 },
      { assetClassName: "TIPS", weight: 0.10 },
      { assetClassName: "Intermediate-Term Tax-Exempt", weight: 0.10 },
      { assetClassName: "High Yield Corporate Bonds", weight: 0.15 },
      { assetClassName: "Gold", weight: 0.05 },
    ],
  },
  {
    name: "Balanced (60/40)",
    description: "60% equity / 40% fixed income and alternatives",
    allocations: [
      { assetClassName: "US Large Cap", weight: 0.30 },
      { assetClassName: "US Mid Cap", weight: 0.10 },
      { assetClassName: "Global ex-US Stock Market", weight: 0.10 },
      { assetClassName: "Emerging Markets", weight: 0.05 },
      { assetClassName: "REIT", weight: 0.05 },
      { assetClassName: "Short Term Treasury", weight: 0.05 },
      { assetClassName: "10-year Treasury", weight: 0.10 },
      { assetClassName: "TIPS", weight: 0.05 },
      { assetClassName: "Intermediate-Term Tax-Exempt", weight: 0.10 },
      { assetClassName: "High Yield Corporate Bonds", weight: 0.10 },
    ],
  },
  {
    name: "Growth (80/20)",
    description: "80% equity / 20% fixed income and alternatives",
    allocations: [
      { assetClassName: "US Large Cap", weight: 0.35 },
      { assetClassName: "US Mid Cap", weight: 0.15 },
      { assetClassName: "US Small Cap", weight: 0.10 },
      { assetClassName: "Global ex-US Stock Market", weight: 0.10 },
      { assetClassName: "Emerging Markets", weight: 0.05 },
      { assetClassName: "REIT", weight: 0.05 },
      { assetClassName: "Short Term Treasury", weight: 0.05 },
      { assetClassName: "10-year Treasury", weight: 0.05 },
      { assetClassName: "High Yield Corporate Bonds", weight: 0.05 },
      { assetClassName: "Gold", weight: 0.05 },
    ],
  },
  {
    name: "Aggressive (100/0)",
    description: "100% equity, no fixed income",
    allocations: [
      { assetClassName: "US Large Cap", weight: 0.40 },
      { assetClassName: "US Mid Cap", weight: 0.15 },
      { assetClassName: "US Small Cap", weight: 0.15 },
      { assetClassName: "Global ex-US Stock Market", weight: 0.15 },
      { assetClassName: "Emerging Markets", weight: 0.10 },
      { assetClassName: "REIT", weight: 0.05 },
    ],
  },
];

export interface SeedCorrelation {
  /** Asset-class name as it appears in DEFAULT_ASSET_CLASSES. */
  classA: string;
  classB: string;
  correlation: number;
}

// Pairwise correlations (91 upper-triangle pairs over the 14 non-inflation
// classes) are loaded from cma-defaults.generated.json (regenerated by
// scripts/recompute-cma.ts). Pairs omitted default to 0 (independent) when the
// matrix is reconstructed in memory — per the eMoney whitepaper (p.5), a missing
// pair is treated as independent. Inflation is intentionally absent from the
// matrix; it is modeled separately by the engine.
//
// Canonical storage is (classA, classB) with classA < classB alphabetically,
// but the matrix-builder tolerates either ordering, so the list is stored in
// matrix (upper-triangle) order for readability.
export const DEFAULT_CORRELATIONS: SeedCorrelation[] =
  cmaDefaults.correlations as SeedCorrelation[];

if (DEFAULT_CORRELATIONS.length !== 91) {
  throw new Error(
    `cma-seed: expected 91 correlations, got ${DEFAULT_CORRELATIONS.length}`,
  );
}
