// src/lib/tax/state-income/data/brackets-2025.ts
// AUTO-GENERATED by scripts/extract-state-tax-data.local.ts. Re-run yearly.
// Source: State_Income_Tax_Engine_2026.xlsx, sheet Tax_Brackets_2025.
import type { BracketTier } from "@/lib/tax/types";
import type { USPSStateCode } from "@/lib/usps-states";
import type { BracketsByStateStatus } from "../types";

// Re-export BracketTier to suppress unused-import lint errors when referenced by consumers.
export type { BracketTier };

export const BRACKETS_2025: Partial<Record<USPSStateCode, BracketsByStateStatus>> = {
  AL: {
    single: [
      { from: 0, to: 500, rate: 0.02 },
      { from: 500, to: 3000, rate: 0.04 },
      { from: 3000, to: null, rate: 0.05 }
    ],
    joint: [
      { from: 0, to: 1000, rate: 0.02 },
      { from: 1000, to: 6000, rate: 0.04 },
      { from: 6000, to: null, rate: 0.05 }
    ],
  },
  AR: {
    single: [
      { from: 0, to: 4500, rate: 0.02 },
      { from: 4500, to: null, rate: 0.039 }
    ],
    joint: [
      { from: 0, to: 4500, rate: 0.02 },
      { from: 4500, to: null, rate: 0.039 }
    ],
  },
  AZ: {
    single: [
      { from: 0, to: null, rate: 0.025 }
    ],
    joint: [
      { from: 0, to: null, rate: 0.025 }
    ],
  },
  CA: {
    single: [
      { from: 0, to: 10756, rate: 0.01 },
      { from: 10756, to: 25499, rate: 0.02 },
      { from: 25499, to: 40245, rate: 0.04 },
      { from: 40245, to: 55866, rate: 0.06 },
      { from: 55866, to: 70606, rate: 0.08 },
      { from: 70606, to: 360659, rate: 0.093 },
      { from: 360659, to: 432787, rate: 0.103 },
      { from: 432787, to: 721314, rate: 0.113 },
      { from: 721314, to: 1000000, rate: 0.123 },
      { from: 1000000, to: null, rate: 0.133 }
    ],
    joint: [
      { from: 0, to: 21512, rate: 0.01 },
      { from: 21512, to: 50998, rate: 0.02 },
      { from: 50998, to: 80490, rate: 0.04 },
      { from: 80490, to: 111732, rate: 0.06 },
      { from: 111732, to: 141732, rate: 0.08 },
      { from: 141732, to: 721318, rate: 0.093 },
      { from: 721318, to: 865574, rate: 0.103 },
      { from: 865574, to: 1000000, rate: 0.113 },
      { from: 1000000, to: 1442628, rate: 0.123 },
      { from: 1442628, to: null, rate: 0.133 }
    ],
  },
  CO: {
    single: [
      { from: 0, to: null, rate: 0.044 }
    ],
    joint: [
      { from: 0, to: null, rate: 0.044 }
    ],
  },
  CT: {
    single: [
      { from: 0, to: 10000, rate: 0.02 },
      { from: 10000, to: 50000, rate: 0.045 },
      { from: 50000, to: 100000, rate: 0.055 },
      { from: 100000, to: 200000, rate: 0.06 },
      { from: 200000, to: 250000, rate: 0.065 },
      { from: 250000, to: 500000, rate: 0.069 },
      { from: 500000, to: null, rate: 0.0699 }
    ],
    joint: [
      { from: 0, to: 20000, rate: 0.02 },
      { from: 20000, to: 100000, rate: 0.045 },
      { from: 100000, to: 200000, rate: 0.055 },
      { from: 200000, to: 400000, rate: 0.06 },
      { from: 400000, to: 500000, rate: 0.065 },
      { from: 500000, to: 1000000, rate: 0.069 },
      { from: 1000000, to: null, rate: 0.0699 }
    ],
  },
  DC: {
    single: [
      { from: 0, to: 10000, rate: 0.04 },
      { from: 10000, to: 40000, rate: 0.06 },
      { from: 40000, to: 60000, rate: 0.065 },
      { from: 60000, to: 250000, rate: 0.085 },
      { from: 250000, to: 500000, rate: 0.0925 },
      { from: 500000, to: 1000000, rate: 0.0975 },
      { from: 1000000, to: null, rate: 0.1075 }
    ],
    joint: [
      { from: 0, to: 10000, rate: 0.04 },
      { from: 10000, to: 40000, rate: 0.06 },
      { from: 40000, to: 60000, rate: 0.065 },
      { from: 60000, to: 250000, rate: 0.085 },
      { from: 250000, to: 500000, rate: 0.0925 },
      { from: 500000, to: 1000000, rate: 0.0975 },
      { from: 1000000, to: null, rate: 0.1075 }
    ],
  },
  DE: {
    single: [
      { from: 2000, to: 5000, rate: 0.022 },
      { from: 5000, to: 10000, rate: 0.039 },
      { from: 10000, to: 20000, rate: 0.048 },
      { from: 20000, to: 25000, rate: 0.052 },
      { from: 25000, to: 60000, rate: 0.0555 },
      { from: 60000, to: null, rate: 0.066 }
    ],
    joint: [
      { from: 2000, to: 5000, rate: 0.022 },
      { from: 5000, to: 10000, rate: 0.039 },
      { from: 10000, to: 20000, rate: 0.048 },
      { from: 20000, to: 25000, rate: 0.052 },
      { from: 25000, to: 60000, rate: 0.0555 },
      { from: 60000, to: null, rate: 0.066 }
    ],
  },
  GA: {
    single: [
      { from: 0, to: null, rate: 0.0539 }
    ],
    joint: [
      { from: 0, to: null, rate: 0.0539 }
    ],
  },
  HI: {
    single: [
      { from: 0, to: 9600, rate: 0.014 },
      { from: 9600, to: 14400, rate: 0.032 },
      { from: 14400, to: 19200, rate: 0.055 },
      { from: 19200, to: 24000, rate: 0.064 },
      { from: 24000, to: 36000, rate: 0.068 },
      { from: 36000, to: 48000, rate: 0.072 },
      { from: 48000, to: 125000, rate: 0.076 },
      { from: 125000, to: 175000, rate: 0.079 },
      { from: 175000, to: 225000, rate: 0.0825 },
      { from: 225000, to: 275000, rate: 0.09 },
      { from: 275000, to: 325000, rate: 0.1 },
      { from: 325000, to: null, rate: 0.11 }
    ],
    joint: [
      { from: 0, to: 19200, rate: 0.014 },
      { from: 19200, to: 28800, rate: 0.032 },
      { from: 28800, to: 38400, rate: 0.055 },
      { from: 38400, to: 48000, rate: 0.064 },
      { from: 48000, to: 72000, rate: 0.068 },
      { from: 72000, to: 96000, rate: 0.072 },
      { from: 96000, to: 250000, rate: 0.076 },
      { from: 250000, to: 350000, rate: 0.079 },
      { from: 350000, to: 450000, rate: 0.0825 },
      { from: 450000, to: 550000, rate: 0.09 },
      { from: 550000, to: 650000, rate: 0.1 },
      { from: 650000, to: null, rate: 0.11 }
    ],
  },
  IA: {
    single: [
      { from: 0, to: null, rate: 0.038 }
    ],
    joint: [
      { from: 0, to: null, rate: 0.038 }
    ],
  },
  ID: {
    single: [
      { from: 4673, to: null, rate: 0.05695 }
    ],
    joint: [
      { from: 9346, to: null, rate: 0.05695 }
    ],
  },
  IL: {
    single: [
      { from: 0, to: null, rate: 0.0495 }
    ],
    joint: [
      { from: 0, to: null, rate: 0.0495 }
    ],
  },
  IN: {
    single: [
      { from: 0, to: null, rate: 0.03 }
    ],
    joint: [
      { from: 0, to: null, rate: 0.03 }
    ],
  },
  KS: {
    single: [
      { from: 0, to: 23000, rate: 0.052 },
      { from: 23000, to: null, rate: 0.0558 }
    ],
    joint: [
      { from: 0, to: 46000, rate: 0.052 },
      { from: 46000, to: null, rate: 0.0558 }
    ],
  },
  KY: {
    single: [
      { from: 0, to: null, rate: 0.04 }
    ],
    joint: [
      { from: 0, to: null, rate: 0.04 }
    ],
  },
  LA: {
    single: [
      { from: 0, to: null, rate: 0.03 }
    ],
    joint: [
      { from: 0, to: null, rate: 0.03 }
    ],
  },
  MA: {
    single: [
      { from: 0, to: 1083150, rate: 0.05 },
      { from: 1083150, to: null, rate: 0.09 }
    ],
    joint: [
      { from: 0, to: 1083150, rate: 0.05 },
      { from: 1083150, to: null, rate: 0.09 }
    ],
  },
  MD: {
    single: [
      { from: 0, to: 1000, rate: 0.02 },
      { from: 1000, to: 2000, rate: 0.03 },
      { from: 2000, to: 3000, rate: 0.04 },
      { from: 3000, to: 100000, rate: 0.0475 },
      { from: 100000, to: 125000, rate: 0.05 },
      { from: 125000, to: 150000, rate: 0.0525 },
      { from: 150000, to: 250000, rate: 0.055 },
      { from: 250000, to: null, rate: 0.0575 }
    ],
    joint: [
      { from: 0, to: 1000, rate: 0.02 },
      { from: 1000, to: 2000, rate: 0.03 },
      { from: 2000, to: 3000, rate: 0.04 },
      { from: 3000, to: 150000, rate: 0.0475 },
      { from: 150000, to: 175000, rate: 0.05 },
      { from: 175000, to: 225000, rate: 0.0525 },
      { from: 225000, to: 300000, rate: 0.055 },
      { from: 300000, to: null, rate: 0.0575 }
    ],
  },
  ME: {
    single: [
      { from: 0, to: 26800, rate: 0.058 },
      { from: 26800, to: 63450, rate: 0.0675 },
      { from: 63450, to: null, rate: 0.0715 }
    ],
    joint: [
      { from: 0, to: 53600, rate: 0.058 },
      { from: 53600, to: 126900, rate: 0.0675 },
      { from: 126900, to: null, rate: 0.0715 }
    ],
  },
  MI: {
    single: [
      { from: 0, to: null, rate: 0.0425 }
    ],
    joint: [
      { from: 0, to: null, rate: 0.0425 }
    ],
  },
  MN: {
    single: [
      { from: 0, to: 32570, rate: 0.0535 },
      { from: 32570, to: 106990, rate: 0.068 },
      { from: 106990, to: 198630, rate: 0.0785 },
      { from: 198630, to: null, rate: 0.0985 }
    ],
    joint: [
      { from: 0, to: 47620, rate: 0.0535 },
      { from: 47620, to: 189180, rate: 0.068 },
      { from: 189180, to: 330410, rate: 0.0785 },
      { from: 330410, to: null, rate: 0.0985 }
    ],
  },
  MO: {
    single: [
      { from: 1313, to: 2626, rate: 0.02 },
      { from: 2626, to: 3939, rate: 0.025 },
      { from: 3939, to: 5252, rate: 0.03 },
      { from: 5252, to: 6565, rate: 0.035 },
      { from: 6565, to: 7878, rate: 0.04 },
      { from: 7878, to: 9191, rate: 0.045 },
      { from: 9191, to: null, rate: 0.047 }
    ],
    joint: [
      { from: 1313, to: 2626, rate: 0.02 },
      { from: 2626, to: 3939, rate: 0.025 },
      { from: 3939, to: 5252, rate: 0.03 },
      { from: 5252, to: 6565, rate: 0.035 },
      { from: 6565, to: 7878, rate: 0.04 },
      { from: 7878, to: 9191, rate: 0.045 },
      { from: 9191, to: null, rate: 0.047 }
    ],
  },
  MS: {
    single: [
      { from: 10000, to: null, rate: 0.044 }
    ],
    joint: [
      { from: 10000, to: null, rate: 0.044 }
    ],
  },
  MT: {
    single: [
      { from: 0, to: 21100, rate: 0.047 },
      { from: 21100, to: null, rate: 0.059 }
    ],
    joint: [
      { from: 0, to: 42200, rate: 0.047 },
      { from: 42200, to: null, rate: 0.059 }
    ],
  },
  NC: {
    single: [
      { from: 0, to: null, rate: 0.0425 }
    ],
    joint: [
      { from: 0, to: null, rate: 0.0425 }
    ],
  },
  ND: {
    single: [
      { from: 48475, to: 244825, rate: 0.0195 },
      { from: 244825, to: null, rate: 0.025 }
    ],
    joint: [
      { from: 80975, to: 298075, rate: 0.0195 },
      { from: 298075, to: null, rate: 0.025 }
    ],
  },
  NE: {
    single: [
      { from: 0, to: 4030, rate: 0.0246 },
      { from: 4030, to: 24120, rate: 0.0351 },
      { from: 24120, to: 38870, rate: 0.0501 },
      { from: 38870, to: null, rate: 0.052 }
    ],
    joint: [
      { from: 0, to: 8040, rate: 0.0246 },
      { from: 8040, to: 48250, rate: 0.0351 },
      { from: 48250, to: 77730, rate: 0.0501 },
      { from: 77730, to: null, rate: 0.052 }
    ],
  },
  NJ: {
    single: [
      { from: 0, to: 20000, rate: 0.014 },
      { from: 20000, to: 35000, rate: 0.0175 },
      { from: 35000, to: 40000, rate: 0.035 },
      { from: 40000, to: 75000, rate: 0.05525 },
      { from: 75000, to: 500000, rate: 0.0637 },
      { from: 500000, to: 1000000, rate: 0.0897 },
      { from: 1000000, to: null, rate: 0.1075 }
    ],
    joint: [
      { from: 0, to: 20000, rate: 0.014 },
      { from: 20000, to: 50000, rate: 0.0175 },
      { from: 50000, to: 70000, rate: 0.0245 },
      { from: 70000, to: 80000, rate: 0.035 },
      { from: 80000, to: 150000, rate: 0.05525 },
      { from: 150000, to: 500000, rate: 0.0637 },
      { from: 500000, to: 1000000, rate: 0.0897 },
      { from: 1000000, to: null, rate: 0.1075 }
    ],
  },
  NM: {
    single: [
      { from: 0, to: 5500, rate: 0.015 },
      { from: 5500, to: 16500, rate: 0.032 },
      { from: 16500, to: 33500, rate: 0.043 },
      { from: 33500, to: 66500, rate: 0.047 },
      { from: 66500, to: 210000, rate: 0.049 },
      { from: 210000, to: null, rate: 0.059 }
    ],
    joint: [
      { from: 0, to: 8000, rate: 0.015 },
      { from: 8000, to: 25000, rate: 0.032 },
      { from: 25000, to: 50000, rate: 0.043 },
      { from: 50000, to: 100000, rate: 0.047 },
      { from: 100000, to: 315000, rate: 0.049 },
      { from: 315000, to: null, rate: 0.059 }
    ],
  },
  NY: {
    single: [
      { from: 0, to: 8500, rate: 0.04 },
      { from: 8500, to: 11700, rate: 0.045 },
      { from: 11700, to: 13900, rate: 0.0525 },
      { from: 13900, to: 80650, rate: 0.055 },
      { from: 80650, to: 215400, rate: 0.06 },
      { from: 215400, to: 1077550, rate: 0.0685 },
      { from: 1077550, to: 5000000, rate: 0.0965 },
      { from: 5000000, to: 25000000, rate: 0.103 },
      { from: 25000000, to: null, rate: 0.109 }
    ],
    joint: [
      { from: 0, to: 17150, rate: 0.04 },
      { from: 17150, to: 23600, rate: 0.045 },
      { from: 23600, to: 27900, rate: 0.0525 },
      { from: 27900, to: 161550, rate: 0.055 },
      { from: 161550, to: 323200, rate: 0.06 },
      { from: 323200, to: 2155350, rate: 0.0685 },
      { from: 2155350, to: 5000000, rate: 0.0965 },
      { from: 5000000, to: 25000000, rate: 0.103 },
      { from: 25000000, to: null, rate: 0.109 }
    ],
  },
  OH: {
    single: [
      { from: 26050, to: 100000, rate: 0.0275 },
      { from: 100000, to: null, rate: 0.035 }
    ],
    joint: [
      { from: 26050, to: 100000, rate: 0.0275 },
      { from: 100000, to: null, rate: 0.035 }
    ],
  },
  OK: {
    single: [
      { from: 0, to: 1000, rate: 0.0025 },
      { from: 1000, to: 2500, rate: 0.0075 },
      { from: 2500, to: 3750, rate: 0.0175 },
      { from: 3750, to: 4900, rate: 0.0275 },
      { from: 4900, to: 7200, rate: 0.0375 },
      { from: 7200, to: null, rate: 0.0475 }
    ],
    joint: [
      { from: 0, to: 2000, rate: 0.0025 },
      { from: 2000, to: 5000, rate: 0.0075 },
      { from: 5000, to: 7500, rate: 0.0175 },
      { from: 7500, to: 9800, rate: 0.0275 },
      { from: 9800, to: 14400, rate: 0.0375 },
      { from: 14400, to: null, rate: 0.0475 }
    ],
  },
  OR: {
    single: [
      { from: 0, to: 4400, rate: 0.0475 },
      { from: 4400, to: 11050, rate: 0.0675 },
      { from: 11050, to: 125000, rate: 0.0875 },
      { from: 125000, to: null, rate: 0.099 }
    ],
    joint: [
      { from: 0, to: 8800, rate: 0.0475 },
      { from: 8800, to: 22100, rate: 0.0675 },
      { from: 22100, to: 250000, rate: 0.0875 },
      { from: 250000, to: null, rate: 0.099 }
    ],
  },
  PA: {
    single: [
      { from: 0, to: null, rate: 0.0307 }
    ],
    joint: [
      { from: 0, to: null, rate: 0.0307 }
    ],
  },
  RI: {
    single: [
      { from: 0, to: 79900, rate: 0.0375 },
      { from: 79900, to: 181650, rate: 0.0475 },
      { from: 181650, to: null, rate: 0.0599 }
    ],
    joint: [
      { from: 0, to: 79900, rate: 0.0375 },
      { from: 79900, to: 181650, rate: 0.0475 },
      { from: 181650, to: null, rate: 0.0599 }
    ],
  },
  SC: {
    single: [
      { from: 0, to: 3560, rate: 0 },
      { from: 3560, to: 17830, rate: 0.03 },
      { from: 17830, to: null, rate: 0.062 }
    ],
    joint: [
      { from: 0, to: 3560, rate: 0 },
      { from: 3560, to: 17830, rate: 0.03 },
      { from: 17830, to: null, rate: 0.062 }
    ],
  },
  UT: {
    single: [
      { from: 0, to: null, rate: 0.0455 }
    ],
    joint: [
      { from: 0, to: null, rate: 0.0455 }
    ],
  },
  VA: {
    single: [
      { from: 0, to: 3000, rate: 0.02 },
      { from: 3000, to: 5000, rate: 0.03 },
      { from: 5000, to: 17000, rate: 0.05 },
      { from: 17000, to: null, rate: 0.0575 }
    ],
    joint: [
      { from: 0, to: 3000, rate: 0.02 },
      { from: 3000, to: 5000, rate: 0.03 },
      { from: 5000, to: 17000, rate: 0.05 },
      { from: 17000, to: null, rate: 0.0575 }
    ],
  },
  VT: {
    single: [
      { from: 0, to: 47900, rate: 0.0335 },
      { from: 47900, to: 116000, rate: 0.066 },
      { from: 116000, to: 242000, rate: 0.076 },
      { from: 242000, to: null, rate: 0.0875 }
    ],
    joint: [
      { from: 0, to: 79950, rate: 0.0335 },
      { from: 79950, to: 193300, rate: 0.066 },
      { from: 193300, to: 294600, rate: 0.076 },
      { from: 294600, to: null, rate: 0.0875 }
    ],
  },
  WA: {
    single: [
      { from: 0, to: null, rate: 0.07 }
    ],
    joint: [
      { from: 0, to: null, rate: 0.07 }
    ],
  },
  WI: {
    single: [
      { from: 0, to: 14680, rate: 0.035 },
      { from: 14680, to: 29370, rate: 0.044 },
      { from: 29370, to: 323290, rate: 0.053 },
      { from: 323290, to: null, rate: 0.0765 }
    ],
    joint: [
      { from: 0, to: 19580, rate: 0.035 },
      { from: 19580, to: 39150, rate: 0.044 },
      { from: 39150, to: 431060, rate: 0.053 },
      { from: 431060, to: null, rate: 0.0765 }
    ],
  },
  WV: {
    single: [
      { from: 0, to: 10000, rate: 0.0222 },
      { from: 10000, to: 25000, rate: 0.0296 },
      { from: 25000, to: 40000, rate: 0.0333 },
      { from: 40000, to: 60000, rate: 0.0444 },
      { from: 60000, to: null, rate: 0.0482 }
    ],
    joint: [
      { from: 0, to: 10000, rate: 0.0222 },
      { from: 10000, to: 25000, rate: 0.0296 },
      { from: 25000, to: 40000, rate: 0.0333 },
      { from: 40000, to: 60000, rate: 0.0444 },
      { from: 60000, to: null, rate: 0.0482 }
    ],
  },
};
