// src/lib/tax/state-income/data/brackets-2026.ts
// AUTO-GENERATED by scripts/extract-state-tax-data.local.ts. Re-run yearly.
// Source: State_Income_Tax_Engine_2026.xlsx, sheet Tax_Brackets_2026.
import type { BracketTier } from "@/lib/tax/types";
import type { USPSStateCode } from "@/lib/usps-states";
import type { BracketsByStateStatus } from "../types";

// Re-export BracketTier to suppress unused-import lint errors when referenced by consumers.
export type { BracketTier };

export const BRACKETS_2026: Partial<Record<USPSStateCode, BracketsByStateStatus>> = {
  AL: {
    single: [
      { from: 0, to: 500, rate: 0.02 },
      { from: 500, to: 3000, rate: 0.04 },
      { from: 3000, to: null, rate: 0.05 }
    ],
    joint: [
      { from: 0, to: 1000, rate: 0.02 },
      { from: 1000, to: 6000, rate: 0.04 },
      { from: 6000, to: null, rate: 0.05 }
    ],
  },
  AR: {
    single: [
      { from: 0, to: 4600, rate: 0.02 },
      { from: 4600, to: null, rate: 0.039 }
    ],
    joint: [
      { from: 0, to: 4600, rate: 0.02 },
      { from: 4600, to: null, rate: 0.039 }
    ],
  },
  AZ: {
    single: [
      { from: 0, to: null, rate: 0.025 }
    ],
    joint: [
      { from: 0, to: null, rate: 0.025 }
    ],
  },
  CA: {
    single: [
      { from: 0, to: 11079, rate: 0.01 },
      { from: 11079, to: 26264, rate: 0.02 },
      { from: 26264, to: 41452, rate: 0.04 },
      { from: 41452, to: 57542, rate: 0.06 },
      { from: 57542, to: 72724, rate: 0.08 },
      { from: 72724, to: 371479, rate: 0.093 },
      { from: 371479, to: 445771, rate: 0.103 },
      { from: 445771, to: 742953, rate: 0.113 },
      { from: 742953, to: 1000000, rate: 0.123 },
      { from: 1000000, to: null, rate: 0.133 }
    ],
    joint: [
      { from: 0, to: 22158, rate: 0.01 },
      { from: 22158, to: 52528, rate: 0.02 },
      { from: 52528, to: 82904, rate: 0.04 },
      { from: 82904, to: 115084, rate: 0.06 },
      { from: 115084, to: 145448, rate: 0.08 },
      { from: 145448, to: 742958, rate: 0.093 },
      { from: 742958, to: 891542, rate: 0.103 },
      { from: 891542, to: 1000000, rate: 0.113 },
      { from: 1000000, to: 1485906, rate: 0.123 },
      { from: 1485906, to: null, rate: 0.133 }
    ],
  },
  CO: {
    single: [
      { from: 0, to: null, rate: 0.044 }
    ],
    joint: [
      { from: 0, to: null, rate: 0.044 }
    ],
  },
  CT: {
    single: [
      { from: 0, to: 10000, rate: 0.02 },
      { from: 10000, to: 50000, rate: 0.045 },
      { from: 50000, to: 100000, rate: 0.055 },
      { from: 100000, to: 200000, rate: 0.06 },
      { from: 200000, to: 250000, rate: 0.065 },
      { from: 250000, to: 500000, rate: 0.069 },
      { from: 500000, to: null, rate: 0.0699 }
    ],
    joint: [
      { from: 0, to: 20000, rate: 0.02 },
      { from: 20000, to: 100000, rate: 0.045 },
      { from: 100000, to: 200000, rate: 0.055 },
      { from: 200000, to: 400000, rate: 0.06 },
      { from: 400000, to: 500000, rate: 0.065 },
      { from: 500000, to: 1000000, rate: 0.069 },
      { from: 1000000, to: null, rate: 0.0699 }
    ],
  },
  DC: {
    single: [
      { from: 0, to: 10000, rate: 0.04 },
      { from: 10000, to: 40000, rate: 0.06 },
      { from: 40000, to: 60000, rate: 0.065 },
      { from: 60000, to: 250000, rate: 0.085 },
      { from: 250000, to: 500000, rate: 0.0925 },
      { from: 500000, to: 1000000, rate: 0.0975 },
      { from: 1000000, to: null, rate: 0.1075 }
    ],
    joint: [
      { from: 0, to: 10000, rate: 0.04 },
      { from: 10000, to: 40000, rate: 0.06 },
      { from: 40000, to: 60000, rate: 0.065 },
      { from: 60000, to: 250000, rate: 0.085 },
      { from: 250000, to: 500000, rate: 0.0925 },
      { from: 500000, to: 1000000, rate: 0.0975 },
      { from: 1000000, to: null, rate: 0.1075 }
    ],
  },
  DE: {
    single: [
      { from: 2000, to: 5000, rate: 0.022 },
      { from: 5000, to: 10000, rate: 0.039 },
      { from: 10000, to: 20000, rate: 0.048 },
      { from: 20000, to: 25000, rate: 0.052 },
      { from: 25000, to: 60000, rate: 0.0555 },
      { from: 60000, to: null, rate: 0.066 }
    ],
    joint: [
      { from: 2000, to: 5000, rate: 0.022 },
      { from: 5000, to: 10000, rate: 0.039 },
      { from: 10000, to: 20000, rate: 0.048 },
      { from: 20000, to: 25000, rate: 0.052 },
      { from: 25000, to: 60000, rate: 0.0555 },
      { from: 60000, to: null, rate: 0.066 }
    ],
  },
  GA: {
    single: [
      { from: 0, to: null, rate: 0.0519 }
    ],
    joint: [
      { from: 0, to: null, rate: 0.0519 }
    ],
  },
  HI: {
    single: [
      { from: 0, to: 9600, rate: 0.014 },
      { from: 9600, to: 14400, rate: 0.032 },
      { from: 14400, to: 19200, rate: 0.055 },
      { from: 19200, to: 24000, rate: 0.064 },
      { from: 24000, to: 36000, rate: 0.068 },
      { from: 36000, to: 48000, rate: 0.072 },
      { from: 48000, to: 125000, rate: 0.076 },
      { from: 125000, to: 175000, rate: 0.079 },
      { from: 175000, to: 225000, rate: 0.0825 },
      { from: 225000, to: 275000, rate: 0.09 },
      { from: 275000, to: 325000, rate: 0.1 },
      { from: 325000, to: null, rate: 0.11 }
    ],
    joint: [
      { from: 0, to: 19200, rate: 0.014 },
      { from: 19200, to: 28800, rate: 0.032 },
      { from: 28800, to: 38400, rate: 0.055 },
      { from: 38400, to: 48000, rate: 0.064 },
      { from: 48000, to: 72000, rate: 0.068 },
      { from: 72000, to: 96000, rate: 0.072 },
      { from: 96000, to: 250000, rate: 0.076 },
      { from: 250000, to: 350000, rate: 0.079 },
      { from: 350000, to: 450000, rate: 0.0825 },
      { from: 450000, to: 550000, rate: 0.09 },
      { from: 550000, to: 650000, rate: 0.1 },
      { from: 650000, to: null, rate: 0.11 }
    ],
  },
  IA: {
    single: [
      { from: 0, to: null, rate: 0.038 }
    ],
    joint: [
      { from: 0, to: null, rate: 0.038 }
    ],
  },
  ID: {
    single: [
      { from: 4811, to: null, rate: 0.053 }
    ],
    joint: [
      { from: 9622, to: null, rate: 0.053 }
    ],
  },
  IL: {
    single: [
      { from: 0, to: null, rate: 0.0495 }
    ],
    joint: [
      { from: 0, to: null, rate: 0.0495 }
    ],
  },
  IN: {
    single: [
      { from: 0, to: null, rate: 0.0295 }
    ],
    joint: [
      { from: 0, to: null, rate: 0.0295 }
    ],
  },
  KS: {
    single: [
      { from: 0, to: 23000, rate: 0.052 },
      { from: 23000, to: null, rate: 0.0558 }
    ],
    joint: [
      { from: 0, to: 46000, rate: 0.052 },
      { from: 46000, to: null, rate: 0.0558 }
    ],
  },
  KY: {
    single: [
      { from: 0, to: null, rate: 0.035 }
    ],
    joint: [
      { from: 0, to: null, rate: 0.035 }
    ],
  },
  LA: {
    single: [
      { from: 0, to: null, rate: 0.03 }
    ],
    joint: [
      { from: 0, to: null, rate: 0.03 }
    ],
  },
  MA: {
    single: [
      { from: 0, to: 1083150, rate: 0.05 },
      { from: 1083150, to: null, rate: 0.09 }
    ],
    joint: [
      { from: 0, to: 1083150, rate: 0.05 },
      { from: 1083150, to: null, rate: 0.09 }
    ],
  },
  MD: {
    single: [
      { from: 0, to: 1000, rate: 0.02 },
      { from: 1000, to: 2000, rate: 0.03 },
      { from: 2000, to: 3000, rate: 0.04 },
      { from: 3000, to: 100000, rate: 0.0475 },
      { from: 100000, to: 125000, rate: 0.05 },
      { from: 125000, to: 150000, rate: 0.0525 },
      { from: 150000, to: 250000, rate: 0.055 },
      { from: 250000, to: 500000, rate: 0.0575 },
      { from: 500000, to: 1000000, rate: 0.0625 },
      { from: 1000000, to: null, rate: 0.065 }
    ],
    joint: [
      { from: 0, to: 1000, rate: 0.02 },
      { from: 1000, to: 2000, rate: 0.03 },
      { from: 2000, to: 3000, rate: 0.04 },
      { from: 3000, to: 150000, rate: 0.0475 },
      { from: 150000, to: 175000, rate: 0.05 },
      { from: 175000, to: 225000, rate: 0.0525 },
      { from: 225000, to: 300000, rate: 0.055 },
      { from: 300000, to: 600000, rate: 0.0575 },
      { from: 600000, to: 1200000, rate: 0.0625 },
      { from: 1200000, to: null, rate: 0.065 }
    ],
  },
  ME: {
    single: [
      { from: 0, to: 27399, rate: 0.058 },
      { from: 27399, to: 64849, rate: 0.0675 },
      { from: 64849, to: null, rate: 0.0715 }
    ],
    joint: [
      { from: 0, to: 54849, rate: 0.058 },
      { from: 54849, to: 129749, rate: 0.0675 },
      { from: 129749, to: null, rate: 0.0715 }
    ],
  },
  MI: {
    single: [
      { from: 0, to: null, rate: 0.0425 }
    ],
    joint: [
      { from: 0, to: null, rate: 0.0425 }
    ],
  },
  MN: {
    single: [
      { from: 0, to: 33310, rate: 0.0535 },
      { from: 33310, to: 109430, rate: 0.068 },
      { from: 109430, to: 203150, rate: 0.0785 },
      { from: 203150, to: null, rate: 0.0985 }
    ],
    joint: [
      { from: 0, to: 48700, rate: 0.0535 },
      { from: 48700, to: 193480, rate: 0.068 },
      { from: 193480, to: 337930, rate: 0.0785 },
      { from: 337930, to: null, rate: 0.0985 }
    ],
  },
  MO: {
    single: [
      { from: 1348, to: 2696, rate: 0.02 },
      { from: 2696, to: 4044, rate: 0.025 },
      { from: 4044, to: 5392, rate: 0.03 },
      { from: 5392, to: 6740, rate: 0.035 },
      { from: 6740, to: 8088, rate: 0.04 },
      { from: 8088, to: 9436, rate: 0.045 },
      { from: 9436, to: null, rate: 0.047 }
    ],
    joint: [
      { from: 1348, to: 2696, rate: 0.02 },
      { from: 2696, to: 4044, rate: 0.025 },
      { from: 4044, to: 5392, rate: 0.03 },
      { from: 5392, to: 6740, rate: 0.035 },
      { from: 6740, to: 8088, rate: 0.04 },
      { from: 8088, to: 9436, rate: 0.045 },
      { from: 9436, to: null, rate: 0.047 }
    ],
  },
  MS: {
    single: [
      { from: 10000, to: null, rate: 0.04 }
    ],
    joint: [
      { from: 10000, to: null, rate: 0.04 }
    ],
  },
  MT: {
    single: [
      { from: 0, to: 47500, rate: 0.047 },
      { from: 47500, to: null, rate: 0.0565 }
    ],
    joint: [
      { from: 0, to: 95000, rate: 0.047 },
      { from: 95000, to: null, rate: 0.0565 }
    ],
  },
  NC: {
    single: [
      { from: 0, to: null, rate: 0.0399 }
    ],
    joint: [
      { from: 0, to: null, rate: 0.0399 }
    ],
  },
  ND: {
    single: [
      { from: 48475, to: 244825, rate: 0.0195 },
      { from: 244825, to: null, rate: 0.025 }
    ],
    joint: [
      { from: 80975, to: 298075, rate: 0.0195 },
      { from: 298075, to: null, rate: 0.025 }
    ],
  },
  NE: {
    single: [
      { from: 0, to: 4130, rate: 0.0246 },
      { from: 4130, to: 24760, rate: 0.0351 },
      { from: 24760, to: null, rate: 0.0455 }
    ],
    joint: [
      { from: 0, to: 8250, rate: 0.0246 },
      { from: 8250, to: 49530, rate: 0.0351 },
      { from: 49530, to: null, rate: 0.0455 }
    ],
  },
  NJ: {
    single: [
      { from: 0, to: 20000, rate: 0.014 },
      { from: 20000, to: 35000, rate: 0.0175 },
      { from: 35000, to: 40000, rate: 0.035 },
      { from: 40000, to: 75000, rate: 0.0553 },
      { from: 75000, to: 500000, rate: 0.0637 },
      { from: 500000, to: 1000000, rate: 0.0897 },
      { from: 1000000, to: null, rate: 0.1075 }
    ],
    joint: [
      { from: 0, to: 20000, rate: 0.014 },
      { from: 20000, to: 50000, rate: 0.0175 },
      { from: 50000, to: 70000, rate: 0.0245 },
      { from: 70000, to: 80000, rate: 0.035 },
      { from: 80000, to: 150000, rate: 0.0553 },
      { from: 150000, to: 500000, rate: 0.0637 },
      { from: 500000, to: 1000000, rate: 0.0897 },
      { from: 1000000, to: null, rate: 0.1075 }
    ],
  },
  NM: {
    single: [
      { from: 0, to: 5500, rate: 0.015 },
      { from: 5500, to: 16500, rate: 0.032 },
      { from: 16500, to: 33500, rate: 0.043 },
      { from: 33500, to: 66500, rate: 0.047 },
      { from: 66500, to: 210000, rate: 0.049 },
      { from: 210000, to: null, rate: 0.059 }
    ],
    joint: [
      { from: 0, to: 8000, rate: 0.015 },
      { from: 8000, to: 25000, rate: 0.032 },
      { from: 25000, to: 50000, rate: 0.043 },
      { from: 50000, to: 100000, rate: 0.047 },
      { from: 100000, to: 315000, rate: 0.049 },
      { from: 315000, to: null, rate: 0.059 }
    ],
  },
  NY: {
    single: [
      { from: 0, to: 8500, rate: 0.039 },
      { from: 8500, to: 11700, rate: 0.044 },
      { from: 11700, to: 13900, rate: 0.0515 },
      { from: 13900, to: 80650, rate: 0.054 },
      { from: 80650, to: 215400, rate: 0.059 },
      { from: 215400, to: 1077550, rate: 0.0685 },
      { from: 1077550, to: 5000000, rate: 0.0965 },
      { from: 5000000, to: 25000000, rate: 0.103 },
      { from: 25000000, to: null, rate: 0.109 }
    ],
    joint: [
      { from: 0, to: 17150, rate: 0.039 },
      { from: 17150, to: 23600, rate: 0.044 },
      { from: 23600, to: 27900, rate: 0.0515 },
      { from: 27900, to: 161550, rate: 0.054 },
      { from: 161550, to: 323200, rate: 0.059 },
      { from: 323200, to: 2155350, rate: 0.0685 },
      { from: 2155350, to: 5000000, rate: 0.0965 },
      { from: 5000000, to: 25000000, rate: 0.103 },
      { from: 25000000, to: null, rate: 0.109 }
    ],
  },
  OH: {
    single: [
      { from: 26050, to: null, rate: 0.0275 }
    ],
    joint: [
      { from: 26050, to: null, rate: 0.0275 }
    ],
  },
  OK: {
    single: [
      { from: 3750, to: 4900, rate: 0.025 },
      { from: 4900, to: 7200, rate: 0.035 },
      { from: 7200, to: null, rate: 0.045 }
    ],
    joint: [
      { from: 7500, to: 9800, rate: 0.025 },
      { from: 9800, to: 14400, rate: 0.035 },
      { from: 14400, to: null, rate: 0.045 }
    ],
  },
  OR: {
    single: [
      { from: 0, to: 4550, rate: 0.0475 },
      { from: 4550, to: 11400, rate: 0.0675 },
      { from: 11400, to: 125000, rate: 0.0875 },
      { from: 125000, to: null, rate: 0.099 }
    ],
    joint: [
      { from: 0, to: 9100, rate: 0.0475 },
      { from: 9100, to: 22800, rate: 0.0675 },
      { from: 22800, to: 250000, rate: 0.0875 },
      { from: 250000, to: null, rate: 0.099 }
    ],
  },
  PA: {
    single: [
      { from: 0, to: null, rate: 0.0307 }
    ],
    joint: [
      { from: 0, to: null, rate: 0.0307 }
    ],
  },
  RI: {
    single: [
      { from: 0, to: 82050, rate: 0.0375 },
      { from: 82050, to: 186450, rate: 0.0475 },
      { from: 186450, to: null, rate: 0.0599 }
    ],
    joint: [
      { from: 0, to: 82050, rate: 0.0375 },
      { from: 82050, to: 186450, rate: 0.0475 },
      { from: 186450, to: null, rate: 0.0599 }
    ],
  },
  SC: {
    single: [
      { from: 0, to: 3640, rate: 0 },
      { from: 3640, to: 18230, rate: 0.03 },
      { from: 18230, to: null, rate: 0.06 }
    ],
    joint: [
      { from: 0, to: 3640, rate: 0 },
      { from: 3640, to: 18230, rate: 0.03 },
      { from: 18230, to: null, rate: 0.06 }
    ],
  },
  UT: {
    single: [
      { from: 0, to: null, rate: 0.045 }
    ],
    joint: [
      { from: 0, to: null, rate: 0.045 }
    ],
  },
  VA: {
    single: [
      { from: 0, to: 3000, rate: 0.02 },
      { from: 3000, to: 5000, rate: 0.03 },
      { from: 5000, to: 17000, rate: 0.05 },
      { from: 17000, to: null, rate: 0.0575 }
    ],
    joint: [
      { from: 0, to: 3000, rate: 0.02 },
      { from: 3000, to: 5000, rate: 0.03 },
      { from: 5000, to: 17000, rate: 0.05 },
      { from: 17000, to: null, rate: 0.0575 }
    ],
  },
  VT: {
    single: [
      { from: 0, to: 49400, rate: 0.0335 },
      { from: 49400, to: 119700, rate: 0.066 },
      { from: 119700, to: 249700, rate: 0.076 },
      { from: 249700, to: null, rate: 0.0875 }
    ],
    joint: [
      { from: 0, to: 82500, rate: 0.0335 },
      { from: 82500, to: 199450, rate: 0.066 },
      { from: 199450, to: 304000, rate: 0.076 },
      { from: 304000, to: null, rate: 0.0875 }
    ],
  },
  WA: {
    single: [
      { from: 0, to: 1000000, rate: 0.07 },
      { from: 1000000, to: null, rate: 0.09 }
    ],
    joint: [
      { from: 0, to: 1000000, rate: 0.07 },
      { from: 1000000, to: null, rate: 0.09 }
    ],
  },
  WI: {
    single: [
      { from: 0, to: 15110, rate: 0.035 },
      { from: 15110, to: 51950, rate: 0.044 },
      { from: 51950, to: 332720, rate: 0.053 },
      { from: 332720, to: null, rate: 0.0765 }
    ],
    joint: [
      { from: 0, to: 20150, rate: 0.035 },
      { from: 20150, to: 69260, rate: 0.044 },
      { from: 69260, to: 443630, rate: 0.053 },
      { from: 443630, to: null, rate: 0.0765 }
    ],
  },
  WV: {
    single: [
      { from: 0, to: 10000, rate: 0.0222 },
      { from: 10000, to: 25000, rate: 0.0296 },
      { from: 25000, to: 40000, rate: 0.0333 },
      { from: 40000, to: 60000, rate: 0.0444 },
      { from: 60000, to: null, rate: 0.0482 }
    ],
    joint: [
      { from: 0, to: 10000, rate: 0.0222 },
      { from: 10000, to: 25000, rate: 0.0296 },
      { from: 25000, to: 40000, rate: 0.0333 },
      { from: 40000, to: 60000, rate: 0.0444 },
      { from: 60000, to: null, rate: 0.0482 }
    ],
  },
};
