// src/lib/tax/state-income/__tests__/golden/all-states-2026.test.ts
//
// Golden / snapshot suite — all 51 jurisdictions × 2 profiles for tax year 2026.
//
// The expected values are stored in JSON sibling files and were generated by
// `scripts/generate-state-income-goldens.local.ts`. This is a regression net,
// not a hand-audited correctness suite — any change to the engine that moves
// a number will fail these tests, prompting deliberate baseline updates.
//
// To regenerate after intentional engine changes:
//   npx tsx scripts/generate-state-income-goldens.local.ts
// then `git diff` the JSON files and commit only the intended deltas.

import { describe, it, expect } from "vitest";
import { computeStateIncomeTax } from "../../compute";
import { USPS_STATE_CODES } from "@/lib/usps-states";
import { RETIREE_MFJ_AGE70, WAGE_EARNER_SINGLE_AGE40 } from "./fixtures";
import expectedRetiree from "./golden-expected-2026-retiree.json";
import expectedWage from "./golden-expected-2026-wage.json";

const retireeMap = expectedRetiree as Record<string, number>;
const wageMap = expectedWage as Record<string, number>;

describe("Golden — all 51 jurisdictions 2026", () => {
  describe("retiree-mfj-age70", () => {
    it.each(USPS_STATE_CODES)("%s", (state) => {
      const r = computeStateIncomeTax(RETIREE_MFJ_AGE70(state, 2026));
      const expected = retireeMap[state];
      expect(expected).toBeDefined();
      expect(r.stateTax).toBeCloseTo(expected!, 2);
    });
  });

  describe("wage-earner-single-age40", () => {
    it.each(USPS_STATE_CODES)("%s", (state) => {
      const r = computeStateIncomeTax(WAGE_EARNER_SINGLE_AGE40(state, 2026));
      const expected = wageMap[state];
      expect(expected).toBeDefined();
      expect(r.stateTax).toBeCloseTo(expected!, 2);
    });
  });
});
