// The dictionary Gate 7 reads: given names that are ONLY names.
//
// Hand-written, deliberately. Not fetched from a name service and not generated
// — a downloaded list is exactly the thing that puts "Will", "Grace", "Penny"
// and "August" in front of a gate that reads capitalised words, and a financial
// report is full of capitalised words: every sentence opener, every Title Case
// heading, every month, every fund.
//
// ⚠️ THE ASYMMETRY IS THE WHOLE DESIGN. Gate 7 has no sentence-position
// exemption — "Cooper, your plan holds up" is both the leak the gate exists for
// and the one shape `prompts.ts` permits a name in, so the gate cannot excuse a
// name for sitting first. The entire false-positive defence therefore lives
// HERE, and the two directions do not cost the same:
//
//   a name MISSING from this list  → one leak this gate does not catch, on a
//                                    sample `voice/scrub.ts` is there to have
//                                    taken the names out of first. A second
//                                    line missing it, not a first.
//   a name WRONGLY in this list    → a correct chapter rejected, its one retry
//                                    spent, and a fallback weaker than the prose
//                                    it replaced. Every household, every run.
//
// So this list under-fires by construction, and when an entry is arguable it is
// left out.
//
// THE TEST APPLIED TO EVERY ENTRY: could an advisor write this word, capitalised,
// in a chapter about a family's money? Anything that could is out —
//
//   ordinary words     Will · Mark · Bill · Rich · Frank · Art · Grace · Hope ·
//                      Faith · Rose · Guy · Don · Jack · Sue · Miles · Chance
//   money words        Penny · Sterling · Cash · Bond · Buck · Grant · Max ·
//                      Cliff · Trust · Rich
//   calendar           May · June · April · August · Dawn · Summer · Autumn
//   objects & nature   Hazel · Ivy · Violet · Ruby · Amber · Olive · Lily ·
//                      Iris · Holly · Willow · Pearl · Wren · Reed · Stone
//   trades             Mason · Hunter · Baker · Miller · Fisher · Carter
//   places             Austin · Madison · Charlotte · Savannah · Virginia ·
//                      Georgia · Carolina · Phoenix · Aurora · Brooklyn
//   firms, funds,      Charles (Schwab) · Edward (Jones) · Raymond / James
//   people we quote    (Raymond James) · Morgan · Stanley · Merrill · Dean ·
//                      Franklin · Russell (2000) · Lincoln · Jackson ·
//                      Monte / Carlo (Carlo — Monte Carlo runs in every plan) ·
//                      Warren (Buffett) · Jerome (Powell) · Edgar (the SEC's
//                      filing system) · Troy (ounce)
//
// ONE entry knowingly breaks that test: `cooper`. A cooper makes barrels, and
// the word is dead in modern American prose — no chapter reaches for it. It is
// here because Cooper is this app's own audit household and the leak Gate 7 was
// written against. It is the exception that marks the line, not a licence.
//
// GIVEN names only. A surname that leaks — "the Bradshaws" — is not in here and
// Gate 7 will not see it. `voice/scrub.ts` takes the household name out of a
// sample, and that is the pass surnames are covered by, once the harvest path
// calls it.

/** Names this app has actually seen — its dev fixtures and its audit
 *  households. These are the ones a real leak is most likely to be made of,
 *  because they are the households whose chapters get harvested. */
const SEEN_IN_THIS_APP = [
  "ada",
  "alan",
  "alex",
  "alice",
  "ann",
  "anna",
  "avery",
  "caroline",
  "carol",
  "casey",
  "cooper",
  "dan",
  "dana",
  "emma",
  "jane",
  "jim",
  "john",
  "jonathan",
  "jordan",
  "kevin",
  "linda",
  "michael",
  "noah",
  "riley",
  "sam",
  "sarah",
  "susan",
  "teresa",
  "tom",
  "zoe",
];

/** The common US given names, women then men, with the classes above removed. */
const COMMON_US_GIVEN_NAMES = [
  // women
  "abigail",
  "addison",
  "allison",
  "amanda",
  "amelia",
  "amy",
  "andrea",
  "angela",
  "aria",
  "ashley",
  "athena",
  "aubrey",
  "audrey",
  "barbara",
  "bella",
  "beverly",
  "bonnie",
  "brenda",
  "brittany",
  "catherine",
  "charlene",
  "cheryl",
  "chloe",
  "christina",
  "christine",
  "clara",
  "claire",
  "colleen",
  "cora",
  "courtney",
  "cynthia",
  "danielle",
  "deborah",
  "debra",
  "denise",
  "diana",
  "diane",
  "donna",
  "doris",
  "dorothy",
  "eileen",
  "eleanor",
  "elena",
  "elizabeth",
  "ella",
  "ellen",
  "ellie",
  "emilia",
  "emily",
  "erin",
  "eva",
  "evelyn",
  "frances",
  "gabriella",
  "gail",
  "gloria",
  "hailey",
  "hannah",
  "heather",
  "helen",
  "irene",
  "isabella",
  "isla",
  "jacqueline",
  "janet",
  "janice",
  "jennifer",
  "jessica",
  "joan",
  "josephine",
  "joyce",
  "judith",
  "judy",
  "julia",
  "julie",
  "karen",
  "kathleen",
  "kathryn",
  "kayla",
  "kelly",
  "kimberly",
  "kristen",
  "laura",
  "lauren",
  "layla",
  "leah",
  "leslie",
  "liliana",
  "lillian",
  "lisa",
  "lois",
  "lori",
  "lorraine",
  "louise",
  "lucy",
  "luna",
  "lydia",
  "madeline",
  "madelyn",
  "margaret",
  "maria",
  "marie",
  "marilyn",
  "marjorie",
  "martha",
  "mary",
  "megan",
  "melanie",
  "melissa",
  "michelle",
  "mila",
  "monica",
  "nancy",
  "naomi",
  "natalia",
  "natalie",
  "nicole",
  "nina",
  "nora",
  "olivia",
  "pamela",
  "patricia",
  "penelope",
  "phyllis",
  "quinn",
  "rachel",
  "rebecca",
  "renee",
  "rita",
  "ruth",
  "sadie",
  "samantha",
  "sandra",
  "sara",
  "scarlett",
  "sharon",
  "shirley",
  "sophia",
  "stella",
  "stephanie",
  "tara",
  "taylor",
  "terri",
  "theresa",
  "tiffany",
  "tina",
  "tracy",
  "vanessa",
  "veronica",
  "victoria",
  "vivian",
  "wendy",
  "yvonne",
  // men
  "aaron",
  "adam",
  "albert",
  "alexander",
  "alfred",
  "allen",
  "andrew",
  "anthony",
  "arnold",
  "arthur",
  "barry",
  "benjamin",
  "bradley",
  "brandon",
  "brian",
  "bruce",
  "bryan",
  "calvin",
  "carl",
  "chad",
  "christopher",
  "clarence",
  "clifford",
  "clyde",
  "cody",
  "colin",
  "craig",
  "curtis",
  "damon",
  "daniel",
  "darren",
  "david",
  "dennis",
  "dominic",
  "donald",
  "douglas",
  "dwight",
  "dylan",
  "edwin",
  "elijah",
  "elmer",
  "eric",
  "ernest",
  "ethan",
  "eugene",
  "everett",
  "felix",
  "fernando",
  "floyd",
  "francis",
  "frederick",
  "gabriel",
  "gary",
  "george",
  "gerald",
  "gilbert",
  "glenn",
  "gordon",
  "gregory",
  "harold",
  "harry",
  "harvey",
  "hector",
  "henry",
  "herbert",
  "howard",
  "hugh",
  "ian",
  "isaac",
  "ivan",
  "jacob",
  "jared",
  "jason",
  "javier",
  "jeffrey",
  "jeremy",
  "jesse",
  "joel",
  "jorge",
  "jose",
  "joseph",
  "joshua",
  "juan",
  "justin",
  "keith",
  "kenneth",
  "kurt",
  "kyle",
  "larry",
  "lawrence",
  "leo",
  "leonard",
  "lewis",
  "lloyd",
  "logan",
  "louis",
  "lucas",
  "luis",
  "luke",
  "manuel",
  "marco",
  "marcus",
  "mario",
  "martin",
  "marvin",
  "matthew",
  "maurice",
  "melvin",
  "miguel",
  "milton",
  "mitchell",
  "nathan",
  "nathaniel",
  "neil",
  "nelson",
  "nicholas",
  "norman",
  "oliver",
  "omar",
  "oscar",
  "owen",
  "patrick",
  "paul",
  "pedro",
  "perry",
  "peter",
  "philip",
  "phillip",
  "rafael",
  "ralph",
  "ramon",
  "randall",
  "raul",
  "ricardo",
  "richard",
  "robert",
  "roberto",
  "rodney",
  "roger",
  "roland",
  "ronald",
  "ross",
  "roy",
  "ruben",
  "rudy",
  "ryan",
  "salvador",
  "samuel",
  "saul",
  "scott",
  "sean",
  "sergio",
  "seth",
  "shane",
  "shawn",
  "sidney",
  "simon",
  "spencer",
  "stephen",
  "steven",
  "stuart",
  "ted",
  "theodore",
  "thomas",
  "timothy",
  "tony",
  "travis",
  "tyler",
  "vincent",
  "walter",
  "wallace",
  "wayne",
  "wesley",
  "william",
  "xavier",
  "zachary",
];

/** Lowercased on the way in, so an entry typed with a capital cannot become a
 *  name the gate looks up and can never find. */
export const GIVEN_NAMES: ReadonlySet<string> = new Set(
  [...SEEN_IN_THIS_APP, ...COMMON_US_GIVEN_NAMES].map((name) => name.toLowerCase()),
);
