/**
 * "Spouse" must not appear in anything an advisor or client can read.
 *
 * The second person in a household is a Co-client. The word survives only as a
 * tax or legal term of art (TERMS_OF_ART) or in a file that is factually about
 * the marital relationship (PERMANENT_ALLOWLIST).
 *
 * PENDING is a ratchet, not an allowlist: it lists files the sweep has not
 * reached yet, and it only ever shrinks. A file listed here that is already
 * clean also fails — that stops entries going stale and hiding a regression.
 */
import { describe, it, expect } from "vitest";
import { readFileSync, readdirSync } from "node:fs";
import { join, relative } from "node:path";

const SRC = join(process.cwd(), "src");

/** Tax and legal language. Changing these makes the output wrong, not just differently worded. */
const TERMS_OF_ART =
  /(surviving\s+spouse|spousal|married\s+filing|qualifying\s+widow|marital\s+deduction|ex[-\s]spouse|former\s+spouse|deceased\s+spouse)/i;

/** Files that are legitimately about the marital relationship, forever. */
const PERMANENT_ALLOWLIST = new Set<string>([
  // The CRM records a real relationship (Spouse / Partner / Child), not a planning role.
  "src/lib/crm/relationship-labels.ts",
  "src/components/crm-contact-form.tsx",
  // Teaches the extractor to recognise OTHER software's wording in imported documents.
  "src/lib/extraction/prompts/savings.ts",
  // This test states the word in order to ban it.
  "src/__tests__/co-client-terminology.test.ts",
]);

/** Directory prefixes that are also allowlisted (Bucket C: machine-facing enum documentation). */
const ALLOWLIST_PREFIXES = [
  "src/lib/extraction/prompts/",
  "src/domain/forge/tools/",
];

/**
 * Files the sweep has not reached yet. DELETE YOUR TASK'S FILES AS YOU GO.
 * Replace this array with the paths printed by the command in Step 2.
 */
const PENDING = new Set<string>([

  "src/app/(app)/clients/[id]/assets/balance-sheet-report/balance-sheet-report-content.tsx",
  "src/app/(app)/clients/[id]/details/family/__tests__/family-scenario-rows.test.ts",
  "src/app/(app)/clients/[id]/details/insurance/insurance-content.tsx",
  "src/app/(app)/clients/[id]/details/plan-vs-return/suggestion-card.tsx",
  "src/app/(app)/clients/[id]/estate-planning/lib/__tests__/derive-card-data.test.ts",
  "src/app/(app)/clients/[id]/estate-planning/spine/combined-block.tsx",
  "src/app/(app)/clients/[id]/estate-planning/spine/death-spine.tsx",
  "src/app/(app)/clients/[id]/estate-planning/spine/lib/derive-beneficiary-detail.test.ts",
  "src/app/(app)/clients/[id]/estate-planning/spine/lib/derive-spine-data.test.ts",
  "src/app/(app)/clients/[id]/estate-planning/spine/lib/derive-spine-data.ts",
  "src/app/(app)/clients/[id]/estate-planning/spine/pair-row.tsx",
  "src/app/(app)/clients/[id]/portal/page.tsx",
  "src/app/(app)/clients/[id]/solver/__tests__/li-need-over-time-view.test.tsx",
  "src/app/(app)/clients/[id]/solver/__tests__/live-solver-workspace.test.tsx",
  "src/app/(app)/clients/[id]/solver/__tests__/min-savings-orchestration.test.tsx",
  "src/app/(app)/clients/[id]/solver/__tests__/solver-balance-sheet-panel.test.tsx",
  "src/app/(app)/clients/[id]/solver/__tests__/solver-chart-panel.test.tsx",
  "src/app/(app)/clients/[id]/solver/__tests__/solver-stress-test-disability.test.tsx",
  "src/app/(app)/clients/[id]/solver/solver-content.tsx",
  "src/app/(app)/clients/[id]/solver/solver-field-actions.tsx",
  "src/app/(app)/clients/[id]/solver/solver-row-incomes.tsx",
  "src/app/(app)/clients/[id]/solver/solver-row-life-expectancy.tsx",
  "src/app/(app)/clients/[id]/solver/solver-row-retirement-ages.tsx",
  "src/app/(app)/clients/[id]/solver/solver-row-savings-contributions.tsx",
  "src/app/(app)/clients/[id]/solver/solver-row-social-security.tsx",
  "src/app/(app)/clients/[id]/solver/solver-split-interest-form.tsx",
  "src/app/(app)/clients/[id]/solver/solver-ss-edit-dialog.tsx",
  "src/app/(app)/clients/[id]/solver/solver-tab-life-insurance.tsx",
  "src/app/(app)/clients/[id]/solver/solver-trust-form.tsx",
  "src/app/(app)/clients/new/__tests__/quick-create-form.test.tsx",
  "src/app/(app)/clients/new/quick-create-form.tsx",
  "src/app/(app)/crm/households/[id]/tabs/__tests__/contacts-tab.test.tsx",
  "src/app/(app)/crm/households/[id]/tabs/contacts-tab.tsx",
  "src/app/(app)/risk/[clientId]/risk-detail-content.tsx",
  "src/app/api/clients/[id]/__tests__/put-contact-mirror.test.ts",
  "src/app/api/clients/[id]/accounts/[accountId]/split/route.ts",
  "src/app/api/clients/[id]/accounts/__tests__/owners.test.ts",
  "src/app/api/clients/[id]/balance-sheet-report/export-pdf/route.ts",
  "src/app/api/clients/[id]/entities/[entityId]/assets/__tests__/route.test.ts",
  "src/app/api/clients/[id]/entities/[entityId]/route.ts",
  "src/app/api/clients/[id]/entities/__tests__/route.test.ts",
  "src/app/api/clients/[id]/entities/route.ts",
  "src/app/api/clients/[id]/gifts/__tests__/route.test.ts",
  "src/app/api/clients/[id]/liabilities/__tests__/owners.test.ts",
  "src/app/api/clients/[id]/life-insurance/solve/__tests__/route.test.ts",
  "src/app/api/clients/[id]/medicare-coverage/route.ts",
  "src/app/api/clients/[id]/risk/__tests__/rtq-post.test.ts",
  "src/app/api/clients/[id]/route.ts",
  "src/app/api/clients/[id]/wills/__tests__/route.test.ts",
  "src/app/api/clients/__tests__/post-contact-mirror.test.ts",
  "src/app/api/clients/__tests__/post-spouse-defaults.test.ts",
  "src/app/api/portal/family/__tests__/by-id.test.ts",
  "src/app/api/portal/household/__tests__/route.test.ts",
  "src/components/__tests__/beneficiary-summary.test.tsx",
  "src/components/__tests__/client-identity-menu.test.tsx",
  "src/components/__tests__/estate-flow-change-distribution-dialog.test.tsx",
  "src/components/__tests__/gift-cumulative-table.test.tsx",
  "src/components/__tests__/gift-dialog.test.tsx",
  "src/components/__tests__/income-expenses-view-owner-years.test.tsx",
  "src/components/__tests__/insurance-panel.test.tsx",
  "src/components/__tests__/wills-panel.test.tsx",
  "src/components/__tests__/yearly-estate-charts.test.tsx",
  "src/components/balance-sheet-report-pdf/__tests__/balance-sheet-pdf-document.test.tsx",
  "src/components/balance-sheet-report/__tests__/balance-sheet-report.test.tsx",
  "src/components/balance-sheet-report/__tests__/household-columns.test.ts",
  "src/components/balance-sheet-report/__tests__/view-model.test.ts",
  "src/components/balance-sheet-report/view-model.ts",
  "src/components/balance-sheet-report/year-picker.tsx",
  "src/components/bequest-dialog/__tests__/bequest-dialog.test.tsx",
  "src/components/bequest-dialog/index.tsx",
  "src/components/cashflow-report.tsx",
  "src/components/cashflow/medicare/medicare-year-table.tsx",
  "src/components/cashflow/projection-ages.ts",
  "src/components/charts/__tests__/estate-comparison-chart.test.tsx",
  "src/components/charts/estate-comparison-chart.tsx",
  "src/components/client-identity-menu.tsx",
  "src/components/crm-household-form.tsx",
  "src/components/crm-import-preview.tsx",
  "src/components/deductions-derived-summary.tsx",
  "src/components/deductions-itemized-list.tsx",
  "src/components/disability-panel.tsx",
  "src/components/disability-policy-dialog.tsx",
  "src/components/divorce/__tests__/division-board.test.tsx",
  "src/components/divorce/commit-preview-dialog.tsx",
  "src/components/divorce/divisible-card.tsx",
  "src/components/divorce/division-board.tsx",
  "src/components/divorce/divorce-workbench.tsx",
  "src/components/divorce/settings-rail.tsx",
  "src/components/divorce/split-dialog.tsx",
  "src/components/estate-flow-change-distribution-dialog.tsx",
  "src/components/estate-flow-change-entity-owner-dialog.tsx",
  "src/components/estate-flow-change-owner-dialog.tsx",
  "src/components/estate-flow-remainder-dialog.tsx",
  "src/components/estate-flow-summary-detail-panel.tsx",
  "src/components/estate-flow-view.tsx",
  "src/components/estate-tax-report-view.tsx",
  "src/components/family-view.tsx",
  "src/components/forge/forge-panel.tsx",
  "src/components/forms/__tests__/add-client-form.test.tsx",
  "src/components/forms/__tests__/add-roth-conversion-form.test.tsx",
  "src/components/forms/__tests__/asset-tab-ops.test.ts",
  "src/components/forms/__tests__/beneficiaries-tab.test.tsx",
  "src/components/forms/__tests__/beneficiary-row-list.test.tsx",
  "src/components/forms/__tests__/bequest-recipient-list.test.tsx",
  "src/components/forms/__tests__/inline-owner-cell.test.tsx",
  "src/components/forms/__tests__/ownership-editor.test.tsx",
  "src/components/forms/__tests__/savings-rule-dialog-owner-years.test.tsx",
  "src/components/forms/__tests__/tax-rates-form.test.tsx",
  "src/components/forms/__tests__/trust-ends-select.test.tsx",
  "src/components/forms/add-account-form.tsx",
  "src/components/forms/add-client-form.tsx",
  "src/components/forms/add-deduction-form.tsx",
  "src/components/forms/add-roth-conversion-form.tsx",
  "src/components/forms/add-tax-adjustment-form.tsx",
  "src/components/forms/add-trust-form.tsx",
  "src/components/forms/beneficiaries-tab.tsx",
  "src/components/forms/bequest-recipient-list.tsx",
  "src/components/forms/crt-details-section.tsx",
  "src/components/forms/ownership-editor.tsx",
  "src/components/forms/split-interest-funding-picker.tsx",
  "src/components/forms/tax-rates-form.tsx",
  "src/components/forms/transfers-tab.tsx",
  "src/components/forms/will-residuary-section.tsx",
  "src/components/gift-form.tsx",
  "src/components/household-map/__tests__/goals-board.test.tsx",
  "src/components/household-map/__tests__/household-map-view.test.tsx",
  "src/components/household-map/__tests__/quick-edit-drawer.test.tsx",
  "src/components/household-map/net-worth-board.tsx",
  "src/components/import/__tests__/assumed-chip.test.tsx",
  "src/components/import/__tests__/plan-basics-step.test.tsx",
  "src/components/import/__tests__/review-step-accounts.test.tsx",
  "src/components/import/plan-basics-step.tsx",
  "src/components/import/review-step-family.tsx",
  "src/components/import/review-step-incomes.tsx",
  "src/components/import/review-step-insurance.tsx",
  "src/components/import/review-step-savings.tsx",
  "src/components/import/review-step-wills.tsx",
  "src/components/import/review-wizard.tsx",
  "src/components/import/will-bequest-mapper.tsx",
  "src/components/income-expenses-view.tsx",
  "src/components/income-expenses/__tests__/row.test.tsx",
  "src/components/insurance-panel.tsx",
  "src/components/insurance-policy-details-tab.tsx",
  "src/components/insurance-policy-dialog.tsx",
  "src/components/intake/__tests__/send-client-form.test.tsx",
  "src/components/intake/admin/diff-utils.ts",
  "src/components/intake/admin/review-detail.tsx",
  "src/components/intake/review-step.tsx",
  "src/components/intake/steps/__tests__/accounts-step.test.tsx",
  "src/components/intake/steps/__tests__/estate-step.test.tsx",
  "src/components/intake/steps/__tests__/family-step.test.tsx",
  "src/components/intake/steps/__tests__/goals-step.test.tsx",
  "src/components/intake/steps/__tests__/income-step.test.tsx",
  "src/components/intake/steps/__tests__/property-step.test.tsx",
  "src/components/intake/steps/accounts-step.tsx",
  "src/components/intake/steps/card-list.tsx",
  "src/components/intake/steps/estate-beneficiaries.tsx",
  "src/components/intake/steps/estate-step.tsx",
  "src/components/intake/steps/family-step.tsx",
  "src/components/intake/steps/goals-step.tsx",
  "src/components/intake/steps/income-step.tsx",
  "src/components/intake/steps/property-step.tsx",
  "src/components/intake/welcome-screen.tsx",
  "src/components/medicare/__tests__/medicare-setup-dialog.test.tsx",
  "src/components/medicare/medicare-setup-dialog.tsx",
  "src/components/milestone-year-picker.tsx",
  "src/components/monte-carlo/report-view.tsx",
  "src/components/monte-carlo/yearly-breakdown.tsx",
  "src/components/portal/household-contact-dialog.tsx",
  "src/components/presentations/pages/__tests__/estate-pages-render.test.tsx",
  "src/components/presentations/pages/cover/__tests__/page-pdf.test.tsx",
  "src/components/presentations/pages/estate-summary/page-pdf.tsx",
  "src/components/presentations/pages/life-insurance-summary/page-pdf.tsx",
  "src/components/presentations/pages/retirement-summary/render-smoke.test.tsx",
  "src/components/presentations/registry.tsx",
  "src/components/quick-start/accounts-step.tsx",
  "src/components/quick-start/income-step.tsx",
  "src/components/quick-start/insurance-step.tsx",
  "src/components/report-controls/death-order-toggle.tsx",
  "src/components/risk-profile-pdf/__tests__/risk-profile-pdf-document.test.tsx",
  "src/components/risk/rtq-dialog.tsx",
  "src/components/risk/send-rtq-dialog.tsx",
  "src/components/social-security-card.tsx",
  "src/components/social-security-dialog.tsx",
  "src/components/solver/summaries/__tests__/life-insurance-summary-view.test.tsx",
  "src/components/solver/summaries/estate-summary-view.tsx",
  "src/components/solver/summaries/life-insurance-summary-view.tsx",
  "src/components/solver/summaries/medicare-summary-view.tsx",
  "src/components/state-death-tax-report-view.tsx",
  "src/components/stock-options/future-activity-ledger.tsx",
  "src/components/tax-adjustments-list.tsx",
  "src/components/tax-ledger/tax-ledger-year-picker.tsx",
  "src/components/timeline/timeline-spine.tsx",
  "src/components/unified-clients-table.tsx",
  "src/components/wills-panel.tsx",
  "src/components/yearly-estate-report-view.tsx",
  "src/components/yearly-estate-table.tsx",
  "src/db/schema.ts",
  "src/domain/forge/__tests__/preview.test.ts",
  "src/domain/forge/__tests__/row-lines.test.ts",
  "src/domain/forge/preview.ts",
  "src/engine/__tests__/_fixtures/estate.ts",
  "src/engine/__tests__/capital-loss-carryforward.test.ts",
  "src/engine/__tests__/contribution-limits.test.ts",
  "src/engine/__tests__/death-event-locked-shares.integration.test.ts",
  "src/engine/__tests__/death-event.test.ts",
  "src/engine/__tests__/entity-cashflow.test.ts",
  "src/engine/__tests__/estate-tax-integration.test.ts",
  "src/engine/__tests__/fixtures/married-estate-fixture.ts",
  "src/engine/__tests__/gift-exemption-warning.test.ts",
  "src/engine/__tests__/gift-ledger.test.ts",
  "src/engine/__tests__/income.test.ts",
  "src/engine/__tests__/ira-basis.test.ts",
  "src/engine/__tests__/ira-post-tax-basis-distribution.test.ts",
  "src/engine/__tests__/life-insurance-expiry.test.ts",
  "src/engine/__tests__/life-insurance-payout-visibility.test.ts",
  "src/engine/__tests__/planSupplementalWithdrawal.test.ts",
  "src/engine/__tests__/projection-roth-fill-bracket-depleted.test.ts",
  "src/engine/__tests__/projection-roth-fill-bracket.test.ts",
  "src/engine/__tests__/projection-roth-joint-convergence.test.ts",
  "src/engine/__tests__/projection.entity-distribution.test.ts",
  "src/engine/__tests__/projection.test.ts",
  "src/engine/__tests__/retirement-proration.test.ts",
  "src/engine/__tests__/roth-irmaa-cap-regression.test.ts",
  "src/engine/__tests__/run-projection-with-events.test.ts",
  "src/engine/__tests__/slat-40-year.integration.test.ts",
  "src/engine/__tests__/step-up-cap-gains.test.ts",
  "src/engine/__tests__/stress-disability.test.ts",
  "src/engine/__tests__/surplus-spend.test.ts",
  "src/engine/__tests__/threshold-golden-projection.test.ts",
  "src/engine/__tests__/threshold-household.test.ts",
  "src/engine/contribution-limits.ts",
  "src/engine/death-event/__tests__/business-succession.test.ts",
  "src/engine/death-event/__tests__/drain-attribution.test.ts",
  "src/engine/death-event/__tests__/estate-tax.test.ts",
  "src/engine/death-event/__tests__/final-death.test.ts",
  "src/engine/death-event/__tests__/first-death.test.ts",
  "src/engine/death-event/__tests__/grantor-succession.test.ts",
  "src/engine/death-event/__tests__/inheritance-tax-md-dual.test.ts",
  "src/engine/death-event/__tests__/ird-surviving-spouse.test.ts",
  "src/engine/death-event/__tests__/ird-tax.test.ts",
  "src/engine/death-event/__tests__/life-insurance-integration.test.ts",
  "src/engine/death-event/__tests__/partition-mixed-account-integration.test.ts",
  "src/engine/death-event/__tests__/section-2035-integration.test.ts",
  "src/engine/death-event/__tests__/shared.test.ts",
  "src/engine/death-event/__tests__/survivor-recipient-id.test.ts",
  "src/engine/death-event/__tests__/will-residuary.test.ts",
  "src/engine/death-event/business-succession.ts",
  "src/engine/death-event/first-death.ts",
  "src/engine/death-event/inheritance-tax.ts",
  "src/engine/death-event/section-2035-lookback.ts",
  "src/engine/death-event/shared.ts",
  "src/engine/family-cashflow.ts",
  "src/engine/life-insurance-expiry.ts",
  "src/engine/monteCarlo/__tests__/summarize.test.ts",
  "src/engine/projection.ts",
  "src/engine/scenario/__tests__/applyChanges.test.ts",
  "src/engine/socialSecurity/__tests__/claimAge.test.ts",
  "src/engine/socialSecurity/__tests__/orchestrator.test.ts",
  "src/engine/socialSecurity/__tests__/spousal.test.ts",
  "src/engine/trust-tax/__tests__/apply-trust-annual-pass.test.ts",
  "src/engine/trust-tax/route-dni.ts",
  "src/engine/what-if/__tests__/hypothetical-estate-tax.test.ts",
  "src/engine/what-if/__tests__/life-insurance-need.test.ts",
  "src/engine/what-if/life-insurance-need.ts",
  "src/lib/__tests__/client-search.test.ts",
  "src/lib/__tests__/entity-owners-ops.test.ts",
  "src/lib/__tests__/milestones.test.ts",
  "src/lib/__tests__/onboarding-step-status.test.ts",
  "src/lib/__tests__/owner-labels.test.ts",
  "src/lib/__tests__/plan-horizon.test.ts",
  "src/lib/account-groups/__tests__/mutations.test.ts",
  "src/lib/audit/field-labels.ts",
  "src/lib/balance-sheet/__tests__/attribute.test.ts",
  "src/lib/balance-sheet/__tests__/trust-details.test.ts",
  "src/lib/balance-sheet/trust-details.ts",
  "src/lib/clients/__tests__/mirror-contact-to-crm.test.ts",
  "src/lib/clients/get-client-with-contacts.test.ts",
  "src/lib/compute-cache/assemble-monte-carlo-result.test.ts",
  "src/lib/crm/__tests__/contact-sections.test.ts",
  "src/lib/crm/__tests__/contacts.test.ts",
  "src/lib/crm/__tests__/household-name.test.ts",
  "src/lib/crm/__tests__/households-create.test.ts",
  "src/lib/crm/__tests__/households-family.test.ts",
  "src/lib/crm/__tests__/import-e2e.test.ts",
  "src/lib/crm/__tests__/selectors.test.ts",
  "src/lib/crm/__tests__/sort.test.ts",
  "src/lib/crm/__tests__/sync-household-name.test.ts",
  "src/lib/crm/import/__tests__/rows.test.ts",
  "src/lib/crm/import/columns.ts",
  "src/lib/crm/import/rows.ts",
  "src/lib/divorce/__tests__/allocation-rules.test.ts",
  "src/lib/divorce/__tests__/commit-divorce-plan.test.ts",
  "src/lib/divorce/__tests__/commit-preview.test.ts",
  "src/lib/divorce/__tests__/divisible-objects.test.ts",
  "src/lib/divorce/__tests__/fixtures.ts",
  "src/lib/divorce/__tests__/side-totals.test.ts",
  "src/lib/divorce/commit-divorce-plan.ts",
  "src/lib/divorce/commit-preview.ts",
  "src/lib/divorce/divorce-plans.ts",
  "src/lib/estate/__tests__/adjusted-taxable-gifts.test.ts",
  "src/lib/estate/__tests__/build-will-updates.test.ts",
  "src/lib/estate/__tests__/cleanup-will-recipients.test.ts",
  "src/lib/estate/__tests__/counterfactual.test.ts",
  "src/lib/estate/__tests__/derive-beneficiary-distribution-form.test.ts",
  "src/lib/estate/__tests__/estate-flow-diff.test.ts",
  "src/lib/estate/__tests__/estate-flow-ownership.test.ts",
  "src/lib/estate/__tests__/estate-flow-summary.test.ts",
  "src/lib/estate/__tests__/insured-retirement-year.test.ts",
  "src/lib/estate/__tests__/recipient-label.test.ts",
  "src/lib/estate/__tests__/spousal-household.test.ts",
  "src/lib/estate/__tests__/transfer-report.test.ts",
  "src/lib/estate/death-warning-summary.ts",
  "src/lib/estate/estate-flow-diff.ts",
  "src/lib/estate/estate-flow-ownership.ts",
  "src/lib/estate/transfer-report.ts",
  "src/lib/estate/yearly-estate-report.ts",
  "src/lib/estate/yearly-liquidity-report.test.ts",
  "src/lib/extraction/__tests__/classify.test.ts",
  "src/lib/extraction/__tests__/will-prompt.test.ts",
  "src/lib/extraction/identify-household.ts",
  "src/lib/household-map/__tests__/build-boards.test.ts",
  "src/lib/household-map/__tests__/columns.test.ts",
  "src/lib/household-map/__tests__/goals.test.ts",
  "src/lib/household-map/__tests__/life-expectancy-write.test.ts",
  "src/lib/household-map/__tests__/social-security.test.ts",
  "src/lib/household-map/approximate-milestones.ts",
  "src/lib/household-map/social-security.ts",
  "src/lib/imports/__tests__/commit-modules.test.ts",
  "src/lib/imports/__tests__/import-milestones.test.ts",
  "src/lib/imports/__tests__/living-slot.test.ts",
  "src/lib/imports/__tests__/match.test.ts",
  "src/lib/imports/__tests__/merge.test.ts",
  "src/lib/imports/__tests__/owner-match.test.ts",
  "src/lib/imports/__tests__/plan-builder-core.test.ts",
  "src/lib/imports/__tests__/reconcile-compensation.test.ts",
  "src/lib/imports/assemble/__tests__/gap-fill.test.ts",
  "src/lib/imports/assemble/__tests__/income-timing.test.ts",
  "src/lib/imports/assemble/__tests__/merge-across-files.test.ts",
  "src/lib/imports/assemble/__tests__/plan-basics.test.ts",
  "src/lib/imports/assemble/gap-fill.ts",
  "src/lib/imports/assemble/income-timing.ts",
  "src/lib/imports/assemble/merge-across-files.ts",
  "src/lib/imports/commit/__tests__/clients-identity.test.ts",
  "src/lib/imports/commit/__tests__/plan-basics.test.ts",
  "src/lib/imports/commit/__tests__/savings.test.ts",
  "src/lib/imports/commit/__tests__/timing.test.ts",
  "src/lib/imports/commit/accounts.ts",
  "src/lib/imports/commit/family-resolver.ts",
  "src/lib/imports/commit/incomes.ts",
  "src/lib/imports/merge.ts",
  "src/lib/imports/owner-match.ts",
  "src/lib/imports/planner/__tests__/apply-decisions.test.ts",
  "src/lib/imports/planner/__tests__/fixtures/manifest.ts",
  "src/lib/imports/planner/__tests__/golden-assertions.test.ts",
  "src/lib/inline-edit/__tests__/owner-presets.test.ts",
  "src/lib/inline-edit/__tests__/scenario-fields.test.ts",
  "src/lib/inline-edit/scenario-fields.ts",
  "src/lib/insurance-policies/__tests__/disability-premium-expense.test.ts",
  "src/lib/insurance-policies/__tests__/owner-ref.test.ts",
  "src/lib/insurance-policies/__tests__/schedule-years.test.ts",
  "src/lib/insurance-policies/load-li-inventory.ts",
  "src/lib/intake/__tests__/apply.test.ts",
  "src/lib/intake/__tests__/diff.test.ts",
  "src/lib/intake/__tests__/documents-household.test.ts",
  "src/lib/intake/__tests__/estate.test.ts",
  "src/lib/intake/__tests__/income-years.test.ts",
  "src/lib/intake/__tests__/note-body.test.ts",
  "src/lib/intake/estate.ts",
  "src/lib/intake/note-body.ts",
  "src/lib/life-event-markers.ts",
  "src/lib/life-insurance/__tests__/existing-coverage.test.ts",
  "src/lib/life-insurance/__tests__/need-over-time.test.ts",
  "src/lib/life-insurance/__tests__/test-helpers.ts",
  "src/lib/life-insurance/need-over-time.ts",
  "src/lib/medicare/dbMapper.ts",
  "src/lib/milestones.ts",
  "src/lib/observations/draft.ts",
  "src/lib/onboarding/step-status.ts",
  "src/lib/plan-text/observation-library.ts",
  "src/lib/plan-text/tokens.ts",
  "src/lib/portal/__tests__/greeting-name.test.ts",
  "src/lib/portal/__tests__/load-organizer-map.test.ts",
  "src/lib/portal/__tests__/load-profile-data.test.ts",
  "src/lib/portal/__tests__/portal-networth.test.ts",
  "src/lib/presentations/__tests__/format.test.ts",
  "src/lib/presentations/__tests__/household-name.test.ts",
  "src/lib/presentations/household-name.ts",
  "src/lib/presentations/pages/assumptions/view-model.ts",
  "src/lib/presentations/pages/cash-flow/__tests__/view-model.test.ts",
  "src/lib/presentations/pages/cash-flow/view-model.ts",
  "src/lib/presentations/pages/client-profile/__tests__/view-model.test.ts",
  "src/lib/presentations/pages/client-profile/view-model.ts",
  "src/lib/presentations/pages/early-years-standing/__tests__/deferral-rules.test.ts",
  "src/lib/presentations/pages/early-years-standing/deferral-rules.ts",
  "src/lib/presentations/pages/estate-gift-tax/__tests__/view-model.test.ts",
  "src/lib/presentations/pages/estate-gift-tax/view-model.ts",
  "src/lib/presentations/pages/estate-liquidity/__tests__/view-model.test.ts",
  "src/lib/presentations/pages/estate-summary/__tests__/options.test.ts",
  "src/lib/presentations/pages/estate-summary/summarize-options.ts",
  "src/lib/presentations/pages/estate-transfer/__tests__/view-model.test.ts",
  "src/lib/presentations/pages/estate-transfer/view-model.ts",
  "src/lib/presentations/pages/household-map/__tests__/view-model.test.ts",
  "src/lib/presentations/pages/household-map/view-model.ts",
  "src/lib/presentations/pages/life-insurance-summary/__tests__/view-model.test.ts",
  "src/lib/presentations/pages/life-insurance-summary/view-model.ts",
  "src/lib/presentations/pages/medicare-summary/view-model.ts",
  "src/lib/presentations/pages/retirement-comparison/view-model.test.ts",
  "src/lib/presentations/pages/retirement-summary/__tests__/social-security.test.ts",
  "src/lib/presentations/pages/retirement-summary/__tests__/view-model.test.ts",
  "src/lib/presentations/pages/retirement-summary/social-security.ts",
  "src/lib/presentations/pages/retirement-summary/view-model.ts",
  "src/lib/presentations/pages/scenario-changes/describe/__tests__/will.test.ts",
  "src/lib/presentations/pages/scenario-changes/describe/kinds/plan.ts",
  "src/lib/presentations/pages/scenario-changes/describe/labels.ts",
  "src/lib/presentations/shared/markers.ts",
  "src/lib/presentations/story/__tests__/load-context.test.ts",
  "src/lib/presentations/story/__tests__/load-household.test.ts",
  "src/lib/projection-explain/__tests__/explain.test.ts",
  "src/lib/projection-explain/__tests__/tax-detectors.test.ts",
  "src/lib/projection-explain/__tests__/tax-diff.test.ts",
  "src/lib/projection/resolve-entity.ts",
  "src/lib/quick-start/__tests__/insurance-save.test.ts",
  "src/lib/quick-start/derive.ts",
  "src/lib/retirement/__tests__/derive-retirement-summary.test.ts",
  "src/lib/risk/existing-scores.ts",
  "src/lib/savings/__tests__/salary-options.test.ts",
  "src/lib/savings/salary-options.ts",
  "src/lib/scenario/__tests__/changes-writer.test.ts",
  "src/lib/scenario/__tests__/scenario-changes-resolve.test.ts",
  "src/lib/scenario/describe-change-target.test.ts",
  "src/lib/scenario/describe-change-target.ts",
  "src/lib/schemas/__tests__/expenses.test.ts",
  "src/lib/schemas/__tests__/incomes.test.ts",
  "src/lib/schemas/__tests__/resources.test.ts",
  "src/lib/schemas/__tests__/wills.test.ts",
  "src/lib/schemas/wills.ts",
  "src/lib/solver/__tests__/apply-mutations-disability-premium.test.ts",
  "src/lib/solver/__tests__/apply-mutations.test.ts",
  "src/lib/solver/__tests__/cashflow-year-detail.test.ts",
  "src/lib/solver/__tests__/mutations-to-scenario-changes.test.ts",
  "src/lib/solver/cashflow-year-detail.ts",
  "src/lib/solver/year-cell-drill.ts",
  "src/lib/tax-analysis/findings/business.ts",
  "src/lib/tax-analysis/findings/money-flags.ts",
  "src/lib/tax-ledger/build-diagnostics.test.ts",
  "src/lib/tax-reconciliation/__tests__/apply.test.ts",
  "src/lib/tax-reconciliation/__tests__/rules-assumptions.test.ts",
  "src/lib/tax-reconciliation/__tests__/rules-pensions.test.ts",
  "src/lib/tax-reconciliation/__tests__/rules-social-security.test.ts",
  "src/lib/tax-reconciliation/__tests__/rules-wages.test.ts",
  "src/lib/tax-reconciliation/rules/assumptions.ts",
  "src/lib/tax-reconciliation/rules/social-security.ts",
  "src/lib/tax-reconciliation/rules/wages.ts",
  "src/lib/tax/__tests__/bracket.test.ts",
  "src/lib/tax/__tests__/derive-deductions.test.ts",
  "src/lib/tax/__tests__/senior-deductions.test.ts",
  "src/lib/tax/__tests__/thresholds.test.ts",
  "src/lib/tax/cell-drill/__tests__/_shared.test.ts",
  "src/lib/tax/cell-drill/__tests__/income-breakdown.test.ts",
  "src/lib/tax/state-income/__tests__/compute.test.ts",
  "src/lib/tax/state-inheritance/__tests__/classify.test.ts",
  "src/lib/tax/state-inheritance/__tests__/golden/pa.test.ts",
  "src/lib/tax/state-inheritance/__tests__/special-rules.test.ts",
  "src/lib/tax/state-inheritance/types.ts",
  "src/lib/tax/thresholds.ts",
  "src/lib/timeline/__tests__/detectors/life.test.ts",
]);/** A quoted string literal or a JSX text node — i.e. something a person reads.
 *  Matches case-insensitively.
 */
const DISPLAY = /("[^"\n]*\bspouse\b[^"\n]*")|('[^'\n]*\bspouse\b[^'\n]*')|(>[^<>{}\n]*\bspouse\b[^<>{}\n]*<)|(`[^`\n]*\bspouse\b[^`\n]*`)/gi;

function walk(dir: string): string[] {
  return readdirSync(dir, { withFileTypes: true }).flatMap((e) => {
    const full = join(dir, e.name);
    if (e.isDirectory()) return e.name === "node_modules" ? [] : walk(full);
    return /\.tsx?$/.test(e.name) ? [full] : [];
  });
}

function isAllowlisted(f: string): boolean {
  if (PERMANENT_ALLOWLIST.has(f)) return true;
  if (ALLOWLIST_PREFIXES.some((prefix) => f.startsWith(prefix))) return true;
  return false;
}

function violations(file: string): string[] {
  const text = readFileSync(file, "utf8");
  return [...text.matchAll(DISPLAY)]
    .filter((m) => {
      const hit = m[0];

      // Exclude if matches TERMS_OF_ART
      if (TERMS_OF_ART.test(hit)) return false;

      // Extract the content without delimiters
      const content = hit.slice(1, -1);

      // Exclude if entire string is exactly the bare enum word "spouse" (lowercase only)
      if (content === "spouse") return false;

      // For lowercase "spouse", apply additional exclusions (c) and (d-new).
      // Only apply these rules if the hit contains lowercase "spouse" AND does not contain capitalized "Spouse".
      const hasLowercaseSpouse = /\bspouse\b/.test(hit);
      const hasCapitalizedSpouse = /\bSpouse\b/.test(hit);

      if (hasLowercaseSpouse && !hasCapitalizedSpouse) {
        // c. No space at all in the content (ids, slugs, CSS tokens like border-spouse/30)
        if (!content.includes(" ")) return false;

        // d-new. Match is directly adjacent to hyphen or underscore (fm-spouse, spouse_retirement, etc.)
        const charBefore = text[m.index - 1];
        const charAfter = text[m.index + hit.length];
        if (charBefore === "-" || charBefore === "_" || charAfter === "-" || charAfter === "_") {
          return false;
        }
      }

      return true;
    })
    .map((m) => m[0]);
}

describe("co-client terminology", () => {
  const files = walk(SRC)
    .map((f) => relative(process.cwd(), f))
    .filter((f) => !isAllowlisted(f));

  it("shows no file saying Spouse outside the pending ratchet", () => {
    const offenders = files.filter((f) => !PENDING.has(f) && violations(f).length > 0);
    expect(
      offenders.map((f) => `${f}: ${violations(f).join(" | ")}`),
      "New visible 'Spouse' copy. Use personLabel()/CO_CLIENT_LABEL from src/lib/owner-labels.ts.",
    ).toEqual([]);
  });

  it("holds no stale entry in the ratchet", () => {
    const stale = [...PENDING].filter((f) => violations(f).length === 0);
    expect(stale, "These files are clean — delete them from PENDING.").toEqual([]);
  });
});
