// Every input ONE generation run is written from, in one object.
//
// Two routes need the identical answer and must not derive it twice: the
// generate route writes each chapter's `sourceHash` from this context, and the
// staleness route compares the stored hash against this context rebuilt. Any
// difference between the two — a scenario label, a solve that one of them
// skipped, a voice sample one of them had — changes the prompt, changes the
// hash, and reports every chapter on the report as out of date. It cannot be two
// copies of the same six lines.
//
// The hash itself is NOT here: it is `chapterSourceHash` in `chapters/prompts.ts`,
// so that `generate.ts` calls the same function rather than a matching one.
//
// (`route.ts` may export nothing but handlers, so a shared helper for two routes
// lives here rather than beside either of them.)
import { storyCandidates } from "./chapters/registry";
import { loadStoryContext } from "./load-context";
import type { DocumentRole } from "./repo";
import type { ChapterId, StoryContext } from "./types";
import { loadVoiceProfile, listVoiceSamples } from "./voice/repo";
import { resolveVoice, type StoryVoice } from "./voice/resolve";

export interface StoryRun {
  ctx: StoryContext;
  /**
   * The chapters this run COULD narrate, so the loader can skip the solves
   * behind facts nothing will read. On a base-only run that is both max-spend
   * solves, since the chapter reading them requires a proposal.
   *
   * `storyCandidates` in `chapters/registry.ts` — the same answer the generate
   * route and the chapter list ask for, not a copy of it.
   *
   * ⚠️ NOT the list the generate route finally writes: that one also reads
   * `available` and `hasSomethingToPropose`, both derived from `ctx`, which is
   * what this load RETURNS. So the list going IN is derived from the ref alone,
   * which is everything known before the facts exist.
   *
   * Deliberately looser as a result — a proposal carrying no changes still
   * solves its max spend. That is the correct direction to be wrong in: the
   * list must be a SUPERSET of what gets narrated, or a chapter is written from
   * a pack missing its own facts and prints an honest empty state on a document
   * handed to a client.
   */
  candidates: ChapterId[];
  /**
   * The advisor's voice — a style note and up to four scrubbed exemplars.
   *
   * ⚠️ AN INPUT TO THE HASH (`chapterSourceHash`). The generating side and the
   * staleness side must be handed the identical object, which is what reading it
   * off the run makes automatic. It is no longer the documented empty literal it
   * was through Plans 1 and 2.
   */
  voice: StoryVoice;
}

/**
 * ⚠️ EXPENSIVE. Two projections, a Monte Carlo read, a balance sheet and (on a
 * proposal) two solves. MEASURED 2026-08-14 on a 21-account household with no
 * proposal: 23.2s cold, 4.0s warm. Nothing on a per-keystroke path may call it —
 * which is why the staleness flag is its own endpoint rather than a field on the
 * chapter list the panel reloads after every save.
 */
export async function loadStoryRun(args: {
  clientId: string;
  firmId: string;
  /**
   * Whose voice. The caller's Clerk user id — `loadVoiceProfile` falls back to
   * the firm's row when this advisor has none.
   *
   * ⚠️ Per-advisor means per-CALLER, and the hash is built from what it
   * resolves: a chapter generated by one advisor and then checked for staleness
   * by a colleague is compared against the colleague's voice, so it reads stale
   * until they regenerate it themselves. Firm-wide rows are shared and cost
   * nothing here; a PERSONAL note or sample is what makes two people at one firm
   * disagree.
   */
  advisorUserId: string;
  /** Already resolved by `resolveStoryScenarioId` — "base" or a real id. */
  scenarioId: string;
  documentRole: DocumentRole;
}): Promise<StoryRun> {
  const proposedRef = args.scenarioId === "base" ? null : args.scenarioId;
  const candidates = storyCandidates(args.scenarioId);
  const [ctx, profile, samples] = await Promise.all([
    loadStoryContext({
      clientId: args.clientId,
      firmId: args.firmId,
      proposedRef,
      scenarioLabel: proposedRef ? "the proposed plan" : "Base Case",
      documentRole: args.documentRole,
      chapters: candidates,
    }),
    loadVoiceProfile(args.firmId, args.advisorUserId),
    listVoiceSamples(args.firmId, args.advisorUserId),
  ]);
  return { ctx, candidates, voice: resolveVoice(profile, samples) };
}
