// scripts/extract-state-tax-data.local.ts
// One-off: read the workbook, emit TS data modules for brackets.
// Output is checked into src/lib/tax/state-income/data/. Re-run yearly.
//
// Usage: npx tsx scripts/extract-state-tax-data.local.ts
import * as XLSX from "xlsx";
import * as fs from "node:fs";
import * as path from "node:path";

const WORKBOOK =
  "/Users/danmueller/Documents/brain/40-resources/tax-data/State_Income_Tax_Engine_2026.xlsx";
const OUT_DIR = path.join(
  __dirname,
  "../src/lib/tax/state-income/data"
);

interface BracketRow {
  Code: string;
  "Filing Status": "Single" | "Joint";
  "Marginal Rate": number;
  "Income Over": number;
}

function readSheet<T>(name: string): T[] {
  const wb = XLSX.readFile(WORKBOOK);
  const ws = wb.Sheets[name];
  if (!ws) {
    throw new Error(
      `Sheet "${name}" not found. Available: ${Object.keys(wb.Sheets).join(", ")}`
    );
  }
  return XLSX.utils.sheet_to_json<T>(ws);
}

/** Detect whether rates are in percentage form (e.g. 2.5 instead of 0.025) */
function normalizeRate(raw: number): number {
  // If the max rate > 1, we have percentages — divide by 100.
  // This is checked per-call after we know whether the entire sheet uses percentages.
  return raw;
}

function emitBrackets(year: 2025 | 2026) {
  const rawRows = readSheet<BracketRow>(`Tax_Brackets_${year}`);

  // Detect percentage form: if any rate is > 1 we treat the whole sheet as pct.
  const maxRate = Math.max(...rawRows.map((r) => Number(r["Marginal Rate"])));
  const divisor = maxRate > 1 ? 100 : 1;
  if (divisor === 100) {
    console.log(
      `  [${year}] Detected percentage form (max rate = ${maxRate}); dividing by 100.`
    );
  } else {
    console.log(
      `  [${year}] Rates already in decimal form (max rate = ${maxRate}).`
    );
  }

  const byState: Record<
    string,
    { single: { from: number; rate: number }[]; joint: { from: number; rate: number }[] }
  > = {};

  for (const r of rawRows) {
    const code = String(r.Code).trim();
    if (!code) continue;
    if (!byState[code]) byState[code] = { single: [], joint: [] };
    const tier = {
      from: Number(r["Income Over"]),
      rate: Number(r["Marginal Rate"]) / divisor,
    };
    const status = String(r["Filing Status"]).trim();
    if (status === "Single") {
      byState[code].single.push(tier);
    } else if (status === "Joint") {
      byState[code].joint.push(tier);
    } else {
      console.warn(`  [${year}] Unknown filing status "${status}" for ${code} — skipped`);
    }
  }

  // Sort each status by `from` ascending.
  for (const code of Object.keys(byState)) {
    for (const status of ["single", "joint"] as const) {
      byState[code][status].sort((a, b) => a.from - b.from);
    }
  }

  const renderTiers = (tiers: { from: number; rate: number }[]): string => {
    return tiers
      .map((t, i) => {
        const to =
          i + 1 < tiers.length ? String(tiers[i + 1].from) : "null";
        // Format rate: use toPrecision to avoid floating-point artifacts, then strip trailing zeros.
        const rateStr = parseFloat(t.rate.toPrecision(10)).toString();
        return `      { from: ${t.from}, to: ${to}, rate: ${rateStr} }`;
      })
      .join(",\n");
  };

  const lines: string[] = [
    `// src/lib/tax/state-income/data/brackets-${year}.ts`,
    `// AUTO-GENERATED by scripts/extract-state-tax-data.local.ts. Re-run yearly.`,
    `// Source: State_Income_Tax_Engine_2026.xlsx, sheet Tax_Brackets_${year}.`,
    `import type { BracketTier } from "@/lib/tax/types";`,
    `import type { USPSStateCode } from "@/lib/usps-states";`,
    `import type { BracketsByStateStatus } from "../types";`,
    ``,
    `// Re-export BracketTier to suppress unused-import lint errors when referenced by consumers.`,
    `export type { BracketTier };`,
    ``,
    `export const BRACKETS_${year}: Partial<Record<USPSStateCode, BracketsByStateStatus>> = {`,
  ];

  for (const code of Object.keys(byState).sort()) {
    const { single, joint } = byState[code];
    lines.push(`  ${code}: {`);
    lines.push(`    single: [`);
    if (single.length > 0) {
      lines.push(renderTiers(single));
    }
    lines.push(`    ],`);
    lines.push(`    joint: [`);
    if (joint.length > 0) {
      lines.push(renderTiers(joint));
    }
    lines.push(`    ],`);
    lines.push(`  },`);
  }

  lines.push(`};`, ``);

  const outPath = path.join(OUT_DIR, `brackets-${year}.ts`);
  fs.writeFileSync(outPath, lines.join("\n"));
  console.log(
    `  Wrote ${outPath} — ${Object.keys(byState).length} states`
  );

  // Spot-check: print AZ single, CA single top rate, AL single tiers.
  const az = byState["AZ"];
  const ca = byState["CA"];
  const al = byState["AL"];
  if (az) {
    console.log(
      `  [${year}] AZ single: ${JSON.stringify(az.single)}`
    );
  }
  if (ca) {
    const topCA = ca.single[ca.single.length - 1];
    console.log(
      `  [${year}] CA single top tier: rate=${topCA?.rate}`
    );
  }
  if (al) {
    console.log(
      `  [${year}] AL single tiers: ${al.single.map((t) => t.rate).join(", ")}`
    );
  }
}

interface StdDedRow {
  Code: string; Year: number;
  Single: number; Joint: number;
  "Add'l Age 65+ (Single)": number;
  "Add'l Age 65+ (Joint, per filer)": number;
  "Phase-out / Notes"?: string;
}
function emitStdDeductions() {
  const rows = readSheet<StdDedRow>("Standard_Deductions");
  const byYearState: Record<number, Record<string, StdDedRow>> = {};
  for (const r of rows) {
    if (!byYearState[r.Year]) byYearState[r.Year] = {};
    byYearState[r.Year][r.Code] = r;
  }
  const lines = [
    `// src/lib/tax/state-income/data/std-deductions.ts`,
    `// AUTO-GENERATED. Source: Standard_Deductions sheet.`,
    `import type { USPSStateCode } from "@/lib/usps-states";`,
    `import type { StdDeductionRow } from "../types";`,
    ``,
    `export const STD_DEDUCTIONS: Record<number, Partial<Record<USPSStateCode, StdDeductionRow>>> = {`,
  ];
  for (const y of Object.keys(byYearState).map(Number).sort()) {
    lines.push(`  ${y}: {`);
    for (const code of Object.keys(byYearState[y]).sort()) {
      const r = byYearState[y][code];
      const notes = r["Phase-out / Notes"]
        ? `, notes: ${JSON.stringify(r["Phase-out / Notes"])}` : "";
      lines.push(`    ${code}: { single: ${r.Single}, joint: ${r.Joint}, add65Single: ${r["Add'l Age 65+ (Single)"]}, add65Joint: ${r["Add'l Age 65+ (Joint, per filer)"]}${notes} },`);
    }
    lines.push(`  },`);
  }
  lines.push(`};`, ``);
  fs.writeFileSync(path.join(OUT_DIR, "std-deductions.ts"), lines.join("\n"));
  console.log(`Wrote std-deductions.ts`);
}

interface ExemptionRowRaw {
  Code: string; Year: number;
  Single: number; Joint: number; Dependent: number;
  "Age 65+ Add'l": number;
  Type: "Exemption" | "Credit" | "Credit (dep)" | "None";
  "Phase-out / Notes"?: string;
}
function emitExemptions() {
  const rows = readSheet<ExemptionRowRaw>("Personal_Exemptions");
  const byYearState: Record<number, Record<string, ExemptionRowRaw>> = {};
  for (const r of rows) {
    if (!byYearState[r.Year]) byYearState[r.Year] = {};
    byYearState[r.Year][r.Code] = r;
  }
  const typeMap: Record<string, "exemption" | "credit" | "none"> = {
    Exemption: "exemption", Credit: "credit", "Credit (dep)": "credit", None: "none",
  };
  const lines = [
    `// src/lib/tax/state-income/data/exemptions.ts`,
    `// AUTO-GENERATED. Source: Personal_Exemptions sheet.`,
    `import type { USPSStateCode } from "@/lib/usps-states";`,
    `import type { ExemptionRow } from "../types";`,
    ``,
    `export const EXEMPTIONS: Record<number, Partial<Record<USPSStateCode, ExemptionRow>>> = {`,
  ];
  for (const y of Object.keys(byYearState).map(Number).sort()) {
    lines.push(`  ${y}: {`);
    for (const code of Object.keys(byYearState[y]).sort()) {
      const r = byYearState[y][code];
      const notes = r["Phase-out / Notes"]
        ? `, notes: ${JSON.stringify(r["Phase-out / Notes"])}` : "";
      lines.push(`    ${code}: { single: ${r.Single}, joint: ${r.Joint}, dependent: ${r.Dependent}, add65: ${r["Age 65+ Add'l"]}, type: ${JSON.stringify(typeMap[r.Type] ?? "none")}${notes} },`);
    }
    lines.push(`  },`);
  }
  lines.push(`};`, ``);
  fs.writeFileSync(path.join(OUT_DIR, "exemptions.ts"), lines.join("\n"));
  console.log(`Wrote exemptions.ts`);
}

interface IncomeBaseRowRaw {
  Code: string;
  "Starting Point": string;
  "Tax-Free Interest Add-Back": string;
  "Capital Gains Special Treatment": string;
  "Pre-Tax Retirement Contributions": string;
  "Alimony Treatment": string;
  Notes?: string;
}
function emitIncomeBase() {
  const rows = readSheet<IncomeBaseRowRaw>("Income_Base_Rules");
  const baseMap: Record<string, "federal-agi" | "federal-taxable" | "state-gti"> = {
    "Federal AGI": "federal-agi",
    "Federal Taxable Income": "federal-taxable",
    // catch-all for GTI variants:
  };
  const fallthroughs: string[] = [];
  const lines = [
    `// src/lib/tax/state-income/data/income-base.ts`,
    `// AUTO-GENERATED. Source: Income_Base_Rules sheet.`,
    `import type { USPSStateCode } from "@/lib/usps-states";`,
    `import type { IncomeBaseRule } from "../types";`,
    ``,
    `export const INCOME_BASE_RULES: Partial<Record<USPSStateCode, IncomeBaseRule>> = {`,
  ];
  for (const r of rows.sort((a, b) => a.Code.localeCompare(b.Code))) {
    if (r["Starting Point"] === "N/A") continue;
    const base = baseMap[r["Starting Point"]] ?? "state-gti";
    if (!baseMap[r["Starting Point"]]) {
      fallthroughs.push(`${r.Code}: "${r["Starting Point"]}"`);
    }
    const addback = /Yes/i.test(r["Tax-Free Interest Add-Back"]);
    const preTax = /Subtracted/i.test(r["Pre-Tax Retirement Contributions"]);
    const alimony = /subtra/i.test(r["Alimony Treatment"]);
    const notes = r.Notes ? `, notes: ${JSON.stringify(r.Notes)}` : "";
    lines.push(`  ${r.Code}: { base: ${JSON.stringify(base)}, taxFreeInterestAddback: ${addback}, preTaxRetirementSubtract: ${preTax}, alimonySubtract: ${alimony}${notes} },`);
  }
  lines.push(`};`, ``);
  fs.writeFileSync(path.join(OUT_DIR, "income-base.ts"), lines.join("\n"));
  console.log(`Wrote income-base.ts`);
  if (fallthroughs.length > 0) {
    console.log(`  [income-base] Unexpected Starting Point values (→ state-gti):`);
    for (const f of fallthroughs) console.log(`    ${f}`);
  } else {
    console.log(`  [income-base] No unexpected Starting Point values.`);
  }
}

console.log("Extracting bracket data from workbook...");
emitBrackets(2025);
emitBrackets(2026);
console.log("Extracting std deductions...");
emitStdDeductions();
console.log("Extracting personal exemptions...");
emitExemptions();
console.log("Extracting income base rules...");
emitIncomeBase();
console.log("Done.");
